"""sovos_ouroboros — bounded self-improvement loop.

Per Master Part AU: "Build the generator as clever and autonomous as you
like; keep the ruler bolted to the wall." The generator may evolve
(sovos-ouroboros proposes improvements), but the judge cannot
(JUDGE.lock requires human ratification).

The closed loop:
  1. arena battery → league ratings
  2. identify weakest faction (lowest Glicko-2 rating with n≥3)
  3. classify failure mode (refusal / garbage / factual / etc.)
  4. emit a proposal (recipe re-tune, prompt change, weight delta)
  5. queue for human sign-off (the JUDGE.lock guard)

This module never auto-promotes:
  - a proposal is a signed receipt
  - human ratifies via write_lock or manual approval
  - the generator re-runs the arena and the cycle repeats

The cycle is *closed* (o->arena->league->o) but *bounded* (every step
must pass through a measurement gate).
"""
from __future__ import annotations

import hashlib
import json
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from sovos_league import Faction, Glicko2State, LeagueTable, Match, PANTHEON
from .failure_modes import classify_failure_mode, FailureMode


# === the 3 rails (doctrine) ===

RAIL_FULL_AUTO = "FULL_AUTO"     # probes, ratings, measurement (the loop itself)
RAIL_HUMAN_SIGN = "HUMAN_SIGN"   # gate changes (CURVATURE signature)
RAIL_NEVER_AUTO = "NEVER_AUTO"    # legal-semantic mappings (counsel only)


@dataclass(frozen=True)
class Proposal:
    """One bounded self-improvement proposal.

    Generated by the loop, queued for human sign-off, never auto-promoted.
    """
    id: str                          # sha256 of the contents
    faction: str                     # which model to tune
    failure_mode: str                # FailureMode.value
    diagnosis: str                   # human-readable
    action: str                      # one of: "re-tune", "re-prompt", "re-quantize", "reject"
    new_recipe: Optional[str] = None  # the proposed recipe/prompt/quant
    expected_gain: float = 0.0       # estimated Glicko-2 gain (σ)
    requires: str = RAIL_HUMAN_SIGN   # which rail gates this proposal
    created_at: str = ""
    chain_id: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    def fingerprint(self) -> str:
        canonical = json.dumps(asdict(self), sort_keys=True, separators=(",", ":"))
        return hashlib.sha256(canonical.encode()).hexdigest()[:24]


def _canonical_id(p: Proposal) -> str:
    canonical = json.dumps(asdict(p), sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode()).hexdigest()


def _is_canonical_faction(name: str) -> bool:
    """Judges cannot be tuned (Part AV: 'the judge does not evolve').

    The canonical factions (Zeus, Eunomia, SOV, Sophos, RED) are
    architectural roles, not candidate generators. The ouroboros
    loop must never propose them for tuning.
    """
    from sovos_league import PANTHEON
    canonical_names = {f.name for f in PANTHEON}
    return name in canonical_names


def identify_weakest(
    league: LeagueTable,
    min_matches: int = 3,
) -> Optional[Faction]:
    """Find the faction with the worst (rating - 2*RD) at min_matches.

    Canonical factions (the judges — Zeus, Eunomia, SOV, Sophos, RED)
    are excluded: per Part AV, the judge does not evolve.
    """
    ranked = [
        f for f in league.factions.values()
        if sum(1 for m in league.matches
               if f.name in (m.challenger, m.defender)) >= min_matches
        and not _is_canonical_faction(f.name)
    ]
    if not ranked:
        return None
    return min(ranked, key=lambda f: f.state.rating - 2 * f.state.rd)


def propose_for_failure(
    faction_name: str,
    samples: List[str],
    rail: str = RAIL_HUMAN_SIGN,
) -> Proposal:
    """Given a faction's recent responses, classify the failure mode and
    emit a proposal.

    The proposal is queued; the rail determines who can approve it.
    """
    fm = classify_failure_mode(samples)
    now = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

    # action depends on failure mode
    action_map = {
        FailureMode.GARBAGE.value: "re-quantize",
        FailureMode.OVER_REFUSAL.value: "re-prompt",
        FailureMode.UNDER_REFUSAL.value: "re-tune",
        FailureMode.HALLUCINATION.value: "re-tune",
        FailureMode.SLOW.value: "re-quantize",
        FailureMode.UNKNOWN.value: "reject",
    }
    action = action_map.get(fm.value, "reject")

    diagnosis_map = {
        FailureMode.GARBAGE.value: (
            f"{faction_name} emits garbage tokens (e.g., '????'). "
            "Likely merge artifact or PEFT adapter corruption. "
            "Fix candidate: re-quantize from the source safetensors."
        ),
        FailureMode.OVER_REFUSAL.value: (
            f"{faction_name} refuses even legitimate queries. "
            "Safety alignment is over-tuned. "
            "Fix candidate: re-prompt with explicit engagement cues."
        ),
        FailureMode.UNDER_REFUSAL.value: (
            f"{faction_name} engages with prohibited queries. "
            "Safety alignment is under-tuned. "
            "Fix candidate: re-tune recipe with stronger refusal examples."
        ),
        FailureMode.HALLUCINATION.value: (
            f"{faction_name} fabricates facts confidently. "
            "Fix candidate: re-tune with grounded source data."
        ),
        FailureMode.SLOW.value: (
            f"{faction_name} response time is too high. "
            "Fix candidate: re-quantize to a smaller dtype."
        ),
        FailureMode.UNKNOWN.value: (
            f"{faction_name} has unclear failure pattern. "
            "Recommendation: reject and escalate to human review."
        ),
    }

    proposal = Proposal(
        id="",  # set below
        faction=faction_name,
        failure_mode=fm.value,
        diagnosis=diagnosis_map.get(fm.value, ""),
        action=action,
        new_recipe=None,
        expected_gain=10.0 if fm.value != FailureMode.UNKNOWN.value else 0.0,
        requires=rail,
        created_at=now,
        chain_id=f"0x{hash(faction_name + fm.value) & 0xFFFFFFFF:08x}",
    )
    # compute id from the canonical form
    object.__setattr__(proposal, "id", _canonical_id(proposal))
    return proposal


def cycle(
    league: LeagueTable,
    samples_by_faction: Dict[str, List[str]],
    out_dir: Optional[Path] = None,
) -> Tuple[Optional[Faction], Proposal]:
    """Run one bounded self-improvement cycle.

    Returns (weakest, proposal). The proposal is queued but not applied —
    human ratification required.
    """
    weakest = identify_weakest(league)
    if weakest is None:
        return None, Proposal(
            id="", faction="none", failure_mode="UNKNOWN",
            diagnosis="no faction has enough matches to propose",
            action="reject", requires=RAIL_HUMAN_SIGN,
            created_at=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            chain_id="0x0",
        )
    samples = samples_by_faction.get(weakest.name, [])
    proposal = propose_for_failure(weakest.name, samples)
    if out_dir:
        out_dir = Path(out_dir)
        out_dir.mkdir(parents=True, exist_ok=True)
        # queue the proposal (do not apply)
        queue_path = out_dir / "ouroboros_queue.jsonl"
        with queue_path.open("a") as f:
            f.write(json.dumps(proposal.to_dict()) + "\n")
    return weakest, proposal