-- ============================================================================
-- PRESS BLITZ FULL — 1,076 contacts, ~10-15 minutes
-- Run with: osascript press_blitz.applescript
-- Creates drafts in Mail.app. You then click Send.
-- ============================================================================

property totalCreated : 0
property totalFailed : 0
property logFile : "/Users/nicholas/clawd/PASSPORT_LAUNCH_13JUN/press_send.log"

on logMsg(msg)
    set theFile to open for access logFile with write permission
    write ((current date) as string) & " | " & msg & return to theFile as string
    close access theFile
end logMsg

on createDraft(theEmail, theFirst, theOutlet, theBeat)
    try
        set theSubject to "Open source — the missing A2A primitive, 49 days before the EU cliff"
        set theBody to my buildBody(theFirst, theOutlet, theBeat)
        set newMessage to make new outgoing message with properties {subject:theSubject, content:theBody}
        tell newMessage
            make new to recipient at end of to recipients with properties {address:theEmail}
            set visible to false
        end tell
        set totalCreated to totalCreated + 1
        if (totalCreated mod 100) = 0 then
            logMsg ("OK  | " & totalCreated & " drafts created so far")
        end if
    on error errMsg
        set totalFailed to totalFailed + 1
        logMsg ("ERR | " & theEmail & " | " & errMsg)
    end try
end createDraft

on buildBody(theFirst, theOutlet, theBeat)
    set openerAI to "Since you cover the AI beat for " & theOutlet & ","
    set openerML to "Since you cover the ML beat for " & theOutlet & ","
    set openerEU to "Since you cover EU policy at " & theOutlet & ","
    set openerReg to "Since you cover regulation at " & theOutlet & ","
    set openerSec to "Since you cover security at " & theOutlet & ","
    set openerFin to "Since you cover fintech at " & theOutlet & ","
    set openerDev to "Since you cover dev tools at " & theOutlet & ","
    set openerOS to "Since you cover open source at " & theOutlet & ","
    set openerSU to "Since you cover startups at " & theOutlet & ","
    set openerGen to "As a writer I admire at " & theOutlet & ","

    if theBeat contains "ai" then
        set theOpener to openerAI
    else if theBeat contains "ml" then
        set theOpener to openerML
    else if theBeat contains "eu" then
        set theOpener to openerEU
    else if theBeat contains "reg" then
        set theOpener to openerReg
    else if theBeat contains "sec" then
        set theOpener to openerSec
    else if theBeat contains "fin" then
        set theOpener to openerFin
    else if theBeat contains "dev" then
        set theOpener to openerDev
    else if theBeat contains "open" then
        set theOpener to openerOS
    else if theBeat contains "start" then
        set theOpener to openerSU
    else
        set theOpener to openerGen
    end if

    set theBody to "Hi " & theFirst & "," & return & return & theOpener & " I wanted to flag a launch that lands directly in your wheelhouse." & return & return
    set theBody to theBody & "EU AI Act Article 50 kicks in on 2 Aug 2026 — 49 days from today." & return & return
    set theBody to theBody & "For every new generative AI system shipped into the EU, three requirements become law:" & return
    set theBody to theBody & "1. Mark all AI-generated content (C2PA + watermark)" & return
    set theBody to theBody & "2. Disclose AI involvement" & return
    set theBody to theBody & "3. Remain human-oversightable" & return & return
    set theBody to theBody & "The unanswered question is: how does Agent B on the other side of a transaction KNOW that Agent A meets that bar?" & return & return
    set theBody to theBody & "Today we are shipping the missing primitive: the Agent Compliance Passport." & return & return
    set theBody to theBody & "It is an open-source MCP server (3 tools, 14 tests, 7 files, 28KB of code) that:" & return
    set theBody to theBody & "- Issues Ed25519-signed passports to AI agents" & return
    set theBody to theBody & "- Verifies them offline (100% offline, no API call)" & return
    set theBody to theBody & "- Does the A2A handshake between two agents" & return & return
    set theBody to theBody & "A passport carries the agent identity, a list of 11 compliance frameworks (EU AI Act, Article 50, GDPR, HIPAA, SOC 2, ISO 42001, NIST AI RMF, CRA, DORA, NIS2), and per-claim status — all signed with Ed25519." & return & return
    set theBody to theBody & "Three things you can do:" & return
    set theBody to theBody & "1. Try it: pip install meok-compliance-passport-mcp" & return
    set theBody to theBody & "2. Cover the story: 30-min interview slot, press kit, demo video" & return
    set theBody to theBody & "3. Quote us: press@meok.ai for embargoed coverage before 2 Aug 2026" & return & return
    set theBody to theBody & "GitHub: https://github.com/CSOAI-ORG/meok-compliance-passport-mcp" & return & return
    set theBody to theBody & "Best," & return
    set theBody to theBody & "Nick Templeman" & return
    set theBody to theBody & "Founder, MEOK AI Labs" & return
    set theBody to theBody & "press@meok.ai · https://meok.ai" & return
    return theBody
end buildBody

on run
    logMsg ("=== PRESS BLITZ FULL START ===")
    set theContacts to {
        {"edmcfbasupaffocfbasu@forces.gc.ca", "there", "3rd Canadian Division Support Base Edmonton", "general"},
        {"tips@404media.co", "there", "404 Media", "general"},
        {"dnd.gta.4di.publicaffairs-affairespublique.mdn@forces.gc.ca", "there", "4th Canadian Division Headquarters", "general"},
        {"tips@9to5google.com", "there", "9to5Google", "general"},
        {"tips@9to5mac.com", "there", "9to5Mac", "general"},
        {"compliance@a16z.com", "there", "a16z Podcast", "general"},
        {"news.tips@abc.com", "there", "ABC News", "general"},
        {"netaudr@abc.com", "there", "ABC News", "general"},
        {"jonathan.m.newman@abc.com", "there", "ABC News", "general"},
        {"tara.r.gimbel@abc.com", "there", "ABC News", "general"},
        {"newstips@abc.net.au", "there", "ABC News", "general"},
        {"contact@afp.com", "there", "Agence France-Presse", "general"},
        {"contact@aifund.ai", "there", "AI Fund", "general"},
        {"contact@ainowinstitute.org", "there", "AI Now Institute", "general"},
        {"press@ainowinstitute.org", "there", "AI Now Institute", "general"},
        {"press@turing.ac.uk", "there", "Alan Turing Institute", "general"},
        {"info@turing.ac.uk", "there", "Alan Turing Institute", "general"},
        {"digitaltwins@turing.ac.uk", "there", "Alan Turing Institute", "general"},
        {"fdennehy@turing.ac.uk", "there", "Alan Turing Institute", "general"},
        {"mbailey@turing.ac.uk", "there", "Alan Turing Institute", "general"},
        {"interestgroups@turing.ac.uk", "there", "Alan Turing Institute", "general"},
        {"fakset@aaf.mil.al", "there", "Albanian Armed Forces", "general"},
        {"tips@androidcentral.com", "there", "Android Central", "general"},
        {"segr.dirge@ansa.it", "there", "ANSA", "general"},
        {"seg.dirgio@ansa.it", "there", "ANSA", "general"},
        {"commerciale@ansa.it", "there", "ANSA", "general"},
        {"amministrazione@ansa.it", "there", "ANSA", "general"},
        {"cv@ansa.it", "there", "ANSA", "general"},
        {"rcc@ansa.it", "there", "ANSA", "general"},
        {"cronache@ansa.it", "there", "ANSA", "general"},
        {"cultura@ansa.it", "there", "ANSA", "general"},
        {"economia@ansa.it", "there", "ANSA", "general"},
        {"esteri@ansa.it", "there", "ANSA", "general"},
        {"immagini@ansa.it", "there", "ANSA", "general"},
        {"politica@ansa.it", "there", "ANSA", "general"},
        {"redazione.specializzati@ansa.it", "there", "ANSA", "general"},
        {"sport@ansa.it", "there", "ANSA", "general"},
        {"internet@ansa.it", "there", "ANSA", "general"},
        {"dario@anthropic.com", "there", "Anthropic", "general"},
        {"press@arstechnica.com", "there", "Ars Technica", "general"},
        {"tellus@arstechnica.com", "there", "Ars Technica", "general"},
        {"arstechnica@cndservice.com", "there", "Ars Technica", "general"},
        {"mediarelations@ap.org", "there", "Associated Press", "general"},
        {"info@ap.org", "there", "Associated Press", "general"},
        {"leaston@ap.org", "there", "Associated Press", "general"},
        {"pmaks@ap.org", "there", "Associated Press", "general"},
        {"nmeir@ap.org", "there", "Associated Press", "general"},
        {"info@atlanticcouncil.org", "there", "Atlantic Council", "general"},
        {"tips@axios.com", "there", "Axios", "general"},
        {"newswatch@bbc.co.uk", "there", "BBC", "general"},
        {"yourvoice@bbc.co.uk", "there", "BBC", "general"},
        {"news.partnerships@bbc.co.uk", "there", "BBC", "general"},
        {"shared.dataunit@bbc.co.uk", "there", "BBC", "general"},
        {"press.office@bbc.co.uk", "there", "BBC", "general"},
        {"newsonline.errors@bbc.co.uk", "there", "BBC", "general"},
        {"linkedin@bentsoapbox.com", "there", "Ben Thompson", "general"},
        {"email@stratechery.com", "there", "Ben Thompson", "general"},
        {"support@stratechery.com", "there", "Ben Thompson", "general"},
        {"admin@stratechery.com", "there", "Ben Thompson", "general"},
        {"release@bloomberg.net", "there", "Bloomberg", "general"},
        {"bnbrazil@bloomberg.net", "there", "Bloomberg", "general"},
        {"newsalert@bloomberg.net", "there", "Bloomberg", "general"},
        {"tips2@bloomberg.net", "there", "Bloomberg", "general"},
        {"standards@bloomberg.net", "there", "Bloomberg", "general"},
        {"letters@bloomberg.net", "there", "Bloomberg", "general"},
        {"media@brookings.edu", "there", "Brookings Institution", "general"},
        {"gsmedia@brookings.edu", "there", "Brookings Institution", "general"},
        {"esmedia@brookings.edu", "there", "Brookings Institution", "general"},
        {"fpmedia@brookings.edu", "there", "Brookings Institution", "general"},
        {"globalmedia@brookings.edu", "there", "Brookings Institution", "general"},
        {"metromediarelations@brookings.edu", "there", "Brookings Institution", "general"},
        {"crisis@mfa.bg", "there", "Bulgarian Ministry of Foreign Affairs", "general"},
        {"consular@mfa.bg", "there", "Bulgarian Ministry of Foreign Affairs", "general"},
        {"tips@businessinsider.com", "there", "Business Insider", "general"},
        {"i-dot-ai-enquiries@cabinetoffice.gov.uk", "there", "Cabinet Office AI", "general"},
        {"ai.gcs@cabinetoffice.gov.uk", "there", "Cabinet Office AI", "general"},
        {"ai.security@digital.cabinet-office.gov.uk", "there", "Cabinet Office AI", "general"},
        {"dapa_issues-dapa_enjeux@forces.gc.ca", "there", "Canadian Army Headquarters", "general"},
        {"mlo-blm@forces.gc.ca", "there", "Canadian Department of National Defence", "general"},
        {"cfbesquimalt@outlook.com", "there", "Canadian Forces Base Esquimalt", "general"},
        {"casey@platformer.news", "there", "Casey Newton", "general"},
        {"casey@theverge.com", "there", "Casey Newton", "general"},
        {"cnewton@gmail.com", "there", "Casey Newton", "general"},
        {"ask@cbc.ca", "there", "CBC", "general"},
        {"cbcpr@cbc.ca", "there", "CBC", "general"},
        {"cbcnewsottawa@cbc.ca", "there", "CBC", "general"},
        {"ottawamorning@cbc.ca", "there", "CBC", "general"},
        {"bctoday@cbc.ca", "there", "CBC", "general"},
        {"chuck.thompson@cbc.ca", "there", "CBC", "general"},
        {"cbcnews@cbc.ca", "there", "CBC News", "general"},
        {"desk@cbs2ny.com", "there", "CBS News", "general"},
        {"weekend@cbsnews.com", "there", "CBS News", "general"},
        {"grahams@cbsnews.com", "there", "CBS News", "general"},
        {"huffr@cbsnews.com", "there", "CBS News", "general"},
        {"investigates@cbsnews.com", "there", "CBS News", "general"},
        {"facethenation@cbsnews.com", "there", "CBS News", "general"},
        {"schavez@csis.org", "there", "Center for Strategic and International Studies (CSIS)", "general"},
        {"externalrelations@csis.org", "there", "Center for Strategic and International Studies (CSIS)", "general"},
        {"press_enquiries@channel4.co.uk", "there", "Channel 4", "general"},
        {"news@channel4.com", "there", "Channel 4 News", "general"},
        {"pressoffice@chathamhouse.org", "there", "Chatham House", "general"},
        {"contact@chathamhouse.org", "there", "Chatham House", "general"},
        {"news@cityam.com", "there", "City AM", "general"},
        {"press@cnet.com", "there", "CNET", "general"},
        {"tips@cnet.com", "there", "CNET", "general"},
        {"emily.kuhn@cnn.com", "there", "CNN", "general"},
        {"shani.george@cnn.com", "there", "CNN", "general"},
        {"cnn@cnn.com", "there", "CNN General", "general"},
        {"tips@cnn.com", "there", "CNN Tips", "general"},
        {"communications@cfr.org", "there", "Council on Foreign Relations", "general"},
        {"press@morh.hr", "there", "Croatian Ministry of Defence", "general"},
        {"kabinet@morh.hr", "there", "Croatian Ministry of Defence", "general"},
        {"news@bellmedia.ca", "there", "CTV", "general"},
        {"newschannel@ctv.ca", "there", "CTV", "general"},
        {"w5@bellmedia.ca", "there", "CTV", "general"},
        {"webformtips@bellmedia.ca", "there", "CTV", "general"},
        {"ctvmontrealnews@bellmedia.ca", "there", "CTV", "general"},
        {"montrealweb@ctv.ca", "there", "CTV", "general"},
        {"breakingnews@cp24.com", "there", "CTV", "general"},
        {"ctvnewstips@bellmedia.ca", "there", "CTV News", "general"},
        {"e-podatelnamo@army.cz", "there", "Czech Ministry of Defence", "general"},
        {"posta@army.cz", "there", "Czech Ministry of Defence", "general"},
        {"feedback@dailymail.co.uk", "there", "Daily Mail", "general"},
        {"corrections@dailymail.co.uk", "there", "Daily Mail", "general"},
        {"david.feldstein@dailymail.co.uk", "there", "Daily Mail", "general"},
        {"letters@dailymail.co.uk", "there", "Daily Mail", "general"},
        {"community@dailymailonline.co.uk", "there", "Daily Mail", "general"},
        {"news@dailymail.co.uk", "there", "Daily Mail", "general"},
        {"pictures@dailymail.co.uk", "there", "Daily Mail", "general"},
        {"tips@dailymail.com", "there", "Daily Mail", "general"},
        {"mirrornews@mirror.co.uk", "there", "Daily Mirror", "general"},
        {"mirrorus.news@reachplc.com", "there", "Daily Mirror", "general"},
        {"alex.wellman@reachplc.com", "there", "Daily Mirror", "general"},
        {"mailbox@mirror.co.uk", "there", "Daily Mirror", "general"},
        {"mirrorbooks@reachplc.com", "there", "Daily Mirror", "general"},
        {"communications@reachplc.com", "there", "Daily Mirror", "general"},
        {"readers@mirror.co.uk", "there", "Daily Mirror", "general"},
        {"ftr@mirror.co.uk", "there", "Daily Mirror", "general"},
        {"fmn@fmn.dk", "there", "Danish Ministry of Defence", "general"},
        {"press@deeplearning.ai", "there", "DeepLearning.AI", "general"},
        {"outreach@darpa.mil", "there", "Defense Advanced Research Projects Agency (DARPA)", "general"},
        {"press@dsit.gov.uk", "there", "Department for Science, Innovation and Technology (DSIT)", "general"},
        {"correspondence@dsit.gov.uk", "there", "Department for Science, Innovation and Technology (DSIT)", "general"},
        {"ari@dsit.gov.uk", "there", "Department for Science, Innovation and Technology (DSIT)", "general"},
        {"tips@digitaltrends.com", "there", "Digital Trends", "general"},
        {"editorial@discovermagazine.com", "there", "Discover Magazine", "general"},
        {"berlin@dpa.com", "there", "dpa", "general"},
        {"foto@dpa.com", "there", "dpa", "general"},
        {"sportreport.berlin@dpa.com", "there", "dpa", "general"},
        {"dpa-rufa@dpa.com", "there", "dpa", "general"},
        {"international@dpa.com", "there", "dpa international", "general"},
        {"faktencheck@dpa.com", "there", "dpa-faktencheck", "general"},
        {"kontakt@dpa-info.com", "there", "dpa-info.com", "general"},
        {"infografik@dpa.com", "there", "dpa-infografik", "general"},
        {"themendienst@dpa.com", "there", "dpa-themendienst", "general"},
        {"efepresidencia@efe.es", "there", "EFE", "general"},
        {"jm.sanz@efe.es", "there", "EFE", "general"},
        {"efeempresas@efe.es", "there", "Efe Empresas", "general"},
        {"info@efeegypt.org", "there", "EFE-Egypt", "general"},
        {"europe@efe.org", "there", "EFE-Europe", "general"},
        {"efeuae@efe.org", "there", "EFE-UAE", "general"},
        {"tips@engadget.com", "there", "Engadget", "general"},
        {"ask@engadget.com", "there", "Engadget", "general"},
        {"info@enisa.europa.eu", "there", "ENISA", "general"},
        {"press@enisa.europa.eu", "there", "ENISA", "general"},
        {"incidentreporting@enisa.europa.eu", "there", "ENISA", "general"},
        {"info@kaitseministeerium.ee", "there", "Estonian Ministry of Defence", "general"},
        {"cnect-aioffice@ec.europa.eu", "there", "EU AI Office", "general"},
        {"cnect-aioffice-recruitment@ec.europa.eu", "there", "EU AI Office", "general"},
        {"infso-desk@ec.europa.eu", "there", "European Commission - DG CONNECT", "general"},
        {"cnect-newsmedia@ec.europa.eu", "there", "European Commission - DG CONNECT", "general"},
        {"edpb@edpb.europa.eu", "there", "European Data Protection Board", "general"},
        {"edpb-dpo@edpb.europa.eu", "there", "European Data Protection Board", "general"},
        {"delphine.colard@europarl.europa.eu", "there", "European Parliament", "general"},
        {"theodoros.georgitsopoulos@europarl.europa.eu", "there", "European Parliament", "general"},
        {"neil.corlett@europarl.europa.eu", "there", "European Parliament", "general"},
        {"federico.degirolamo@europarl.europa.eu", "there", "European Parliament", "general"},
        {"andreas.kleiner@europarl.europa.eu", "there", "European Parliament", "general"},
        {"estefania.narrillos@europarl.europa.eu", "there", "European Parliament", "general"},
        {"viktor.almqvist@europarl.europa.eu", "there", "European Parliament", "general"},
        {"snjezana.kobescak@europarl.europa.eu", "there", "European Parliament", "general"},
        {"elodie.laborie@europarl.europa.eu", "there", "European Parliament", "general"},
        {"eoghan.walsh@europarl.europa.eu", "there", "European Parliament", "general"},
        {"lieven.cosijn@europarl.europa.eu", "there", "European Parliament", "general"},
        {"eszter.zalan@europarl.europa.eu", "there", "European Parliament", "general"},
        {"janis.krastins@europarl.europa.eu", "there", "European Parliament", "general"},
        {"raquel.lopes@europarl.europa.eu", "there", "European Parliament", "general"},
        {"john.schranz@europarl.europa.eu", "there", "European Parliament", "general"},
        {"dorota.kolinska@europarl.europa.eu", "there", "European Parliament", "general"},
        {"arianne.sikken@europarl.europa.eu", "there", "European Parliament", "general"},
        {"thomas.haahr@europarl.europa.eu", "there", "European Parliament", "general"},
        {"dana.popp@europarl.europa.eu", "there", "European Parliament", "general"},
        {"baptiste.chatain@europarl.europa.eu", "there", "European Parliament", "general"},
        {"yasmina.yakimova@europarl.europa.eu", "there", "European Parliament", "general"},
        {"maris.kurme@europarl.europa.eu", "there", "European Parliament", "general"},
        {"gediminas.vilkas@europarl.europa.eu", "there", "European Parliament", "general"},
        {"janne.ojamo@europarl.europa.eu", "there", "European Parliament", "general"},
        {"martina.vass@europarl.europa.eu", "there", "European Parliament", "general"},
        {"hana.raissi@europarl.europa.eu", "there", "European Parliament", "general"},
        {"polona.tedesko@europarl.europa.eu", "there", "European Parliament", "general"},
        {"kyriakos.klosidis@europarl.europa.eu", "there", "European Parliament", "general"},
        {"alessio.incorvaia@europarl.europa.eu", "there", "European Parliament", "general"},
        {"connect@epp.eu", "there", "European People's Party", "general"},
        {"news@standard.co.uk", "there", "Evening Standard", "general"},
        {"subscriptions@fastcompany.com", "there", "Fast Company", "general"},
        {"media@fastcompany.com", "there", "Fast Company", "general"},
        {"acarroll@mansueto.com", "there", "Fast Company", "general"},
        {"tips@fastcompany.com", "there", "Fast Company", "general"},
        {"oig@ftc.gov", "there", "Federal Trade Commission (FTC)", "general"},
        {"opa@ftc.gov", "there", "Federal Trade Commission (FTC)", "general"},
        {"newstips@ft.com", "there", "Financial Times", "general"},
        {"editor@ft.com", "there", "Financial Times", "general"},
        {"ftadviser.newsdesk@ft.com", "there", "Financial Times", "general"},
        {"opinion@ft.com", "there", "Financial Times", "general"},
        {"customer.support@ft.com", "there", "Financial Times", "general"},
        {"letters.editor@ft.com", "there", "Financial Times", "general"},
        {"mediapalvelu@gov.fi", "there", "Finnish Ministry of Defence", "general"},
        {"pr@forbes.com", "there", "Forbes PR", "general"},
        {"pressinquiries@forbes.com", "there", "Forbes Press", "general"},
        {"tips@fortune.com", "there", "Fortune", "general"},
        {"irena.briganti@fox.com", "there", "Fox News", "general"},
        {"caley.cronin@fox.com", "there", "Fox News", "general"},
        {"jessica.ketner@fox.com", "there", "Fox News", "general"},
        {"porter.berry@fox.com", "there", "Fox News", "general"},
        {"press@futureoflife.org", "there", "Future of Life Institute", "general"},
        {"contact@futureoflife.org", "there", "Future of Life Institute", "general"},
        {"policy@futureoflife.org", "there", "Future of Life Institute", "general"},
        {"futures@futureoflife.org", "there", "Future of Life Institute", "general"},
        {"grants@futureoflife.org", "there", "Future of Life Institute", "general"},
        {"bmvgpresse@bmvg.bund.de", "there", "German Federal Ministry of Defence", "general"},
        {"tipbox@gizmodo.com", "there", "Gizmodo", "general"},
        {"editor@gizmodo.com", "there", "Gizmodo", "general"},
        {"tips@gizmodo.com", "there", "Gizmodo", "general"},
        {"edmonton@globalnews.ca", "there", "Global News", "general"},
        {"consumermatters@globalnews.ca", "there", "Global News", "general"},
        {"globalnewstips@globalnews.ca", "there", "Global News", "general"},
        {"letters@globeandmail.com", "there", "Globe and Mail", "general"},
        {"hn@ycombinator.com", "there", "Hacker News", "general"},
        {"catherine.anderson@mail.house.gov", "there", "House Committee on Science, Space, and Technology", "general"},
        {"spectrum@ieee.org", "there", "IEEE Spectrum", "general"},
        {"pressoffice@ico.org.uk", "there", "Information Commissioner's Office (ICO)", "general"},
        {"press@isomorphiclabs.com", "there", "Isomorphic Labs", "general"},
        {"partnering@isomorphiclabs.com", "there", "Isomorphic Labs", "general"},
        {"itvplanning@itn.co.uk", "there", "ITV", "general"},
        {"anglianews@itv.com", "there", "ITV", "general"},
        {"yourstory@itv.com", "there", "ITV", "general"},
        {"channelnews@itv.com", "there", "ITV", "general"},
        {"news@itnproductions.com", "there", "ITV", "general"},
        {"itvnewsmeridian@itv.com", "there", "ITV", "general"},
        {"gmb@itv.com", "there", "ITV", "general"},
        {"news@itv.com", "there", "ITV News", "general"},
        {"jmc@launch.co", "there", "Jason Calacanis", "general"},
        {"jason@calacanis.com", "there", "Jason Calacanis", "general"},
        {"jason.calacanis@gmail.com", "there", "Jason Calacanis", "general"},
        {"jrerecruiter@gmail.com", "there", "Joe Rogan", "general"},
        {"jresponsorship@joerogan.net", "there", "Joe Rogan", "general"},
        {"info@comedymothership.com", "there", "Joe Rogan", "general"},
        {"doctorarzt@gmail.com", "there", "Kara Swisher", "general"},
        {"kara.swisher@hotmail.com", "there", "Kara Swisher", "general"},
        {"kara.swisher@wsj.com", "there", "Kara Swisher", "general"},
        {"kara.swisher@getapeptalk.com", "there", "Kara Swisher", "general"},
        {"kosukegawa.yoichi@kyodonews.jp", "there", "Kyodo News", "general"},
        {"hanada.hitomi@kyodonews.jp", "there", "Kyodo News", "general"},
        {"inbound-t@kyodo-d.jp", "there", "KYODO NEWS DIGITAL", "general"},
        {"kni@kyodonews.com", "there", "Kyodo News International, Inc.", "general"},
        {"lex.research@lexfridman.com", "there", "Lex Fridman", "general"},
        {"lex.business@lexfridman.com", "there", "Lex Fridman", "general"},
        {"lex.personal@lexfridman.com", "there", "Lex Fridman", "general"},
        {"lex.podcast.pitch@lexfridman.com", "there", "Lex Fridman", "general"},
        {"lex.official.contact@lexfridman.com", "there", "Lex Fridman", "general"},
        {"lex.podcast.comment@lexfridman.com", "there", "Lex Fridman", "general"},
        {"lex.speaking@lexfridman.com", "there", "Lex Fridman", "general"},
        {"lex.bugs@lexfridman.com", "there", "Lex Fridman", "general"},
        {"tips@macrumors.com", "there", "MacRumors", "general"},
        {"marlantpublicaffairs@forces.gc.ca", "there", "Maritime Forces Atlantic (Canada)", "general"},
        {"esqpacificnavypublicaffairs@forces.gc.ca", "there", "Maritime Forces Pacific (Canada)", "general"},
        {"press@mashable.com", "there", "Mashable", "general"},
        {"news@mashable.com", "there", "Mashable", "general"},
        {"support@mashable.com", "there", "Mashable", "general"},
        {"tips@mashable.com", "there", "Mashable", "general"},
        {"metronews@wmata.com", "there", "Metro", "general"},
        {"newsroom@oregonmetro.gov", "there", "Metro", "general"},
        {"media@ridemetro.org", "there", "Metro", "general"},
        {"media@metro.ca", "there", "Metro", "general"},
        {"drew.kerr@metrotransit.org", "there", "Metro", "general"},
        {"tips@metro.co.uk", "there", "Metro UK", "general"},
        {"yoshua.bengio@mila.quebec", "there", "Mila", "general"},
        {"medias@mila.quebec", "there", "Mila", "general"},
        {"info@mfa.gov.al", "there", "Ministry for Europe and Foreign Affairs of Albania", "general"},
        {"informimi_mm@mod.gov.al", "there", "Ministry of Defence of Albania", "general"},
        {"tips@mirror.co.uk", "there", "Mirror", "general"},
        {"customer-service@technologyreview.com", "there", "MIT Technology Review", "general"},
        {"press@media.mit.edu", "there", "MIT Technology Review", "general"},
        {"opinion@technologyreview.com", "there", "MIT Technology Review", "general"},
        {"tips@technologyreview.com", "there", "MIT Technology Review", "general"},
        {"msnowpress@ms.now", "there", "MSNBC", "general"},
        {"mediainquiries@msnbc.com", "there", "MSNBC", "general"},
        {"stephen.labaton@nbcuni.com", "there", "MSNBC", "general"},
        {"rachel@msnbc.com", "there", "MSNBC", "general"},
        {"hardball@msnbc.com", "there", "MSNBC", "general"},
        {"joe@msnbc.com", "there", "MSNBC", "general"},
        {"pressoffice@ncsc.gov.uk", "there", "National Cyber Security Centre (NCSC)", "general"},
        {"pressoffice@gchq.gov.uk", "there", "National Cyber Security Centre (NCSC)", "general"},
        {"itlmail@nist.gov", "there", "National Institute of Standards and Technology (NIST)", "general"},
        {"inquiry@nist.gov", "there", "National Institute of Standards and Technology (NIST)", "general"},
        {"alexandra.boss@nist.gov", "there", "National Institute of Standards and Technology (NIST)", "general"},
        {"charles.boutin@nist.gov", "there", "National Institute of Standards and Technology (NIST)", "general"},
        {"brian.gutierrez@nist.gov", "there", "National Institute of Standards and Technology (NIST)", "general"},
        {"jennifer.huergo@nist.gov", "there", "National Institute of Standards and Technology (NIST)", "general"},
        {"csrc-inquiry@nist.gov", "there", "National Institute of Standards and Technology (NIST)", "general"},
        {"letters@nationalpost.com", "there", "National Post", "general"},
        {"rgov@nsf.gov", "there", "National Science Foundation (NSF)", "general"},
        {"info@nsf.gov", "there", "National Science Foundation (NSF)", "general"},
        {"data@nsf.gov", "there", "National Science Foundation (NSF)", "general"},
        {"ncsesweb@nsf.gov", "there", "National Science Foundation (NSF)", "general"},
        {"media@nsf.gov", "there", "National Science Foundation (NSF)", "general"},
        {"sgdewint@nsf.gov", "there", "National Science Foundation (NSF)", "general"},
        {"nature@nature.com", "there", "Nature News", "general"},
        {"tips@nbcuni.com", "there", "NBC News", "general"},
        {"nbcnewsmediarelations@nbcuni.com", "there", "NBC News", "general"},
        {"newsroom@nbcuni.com", "there", "NBC News", "general"},
        {"nightly@nbcuni.com", "there", "NBC News", "general"},
        {"contact.mtp@nbcuni.com", "there", "NBC News", "general"},
        {"letters@newscientist.com", "there", "New Scientist", "general"},
        {"corrections@nytimes.com", "there", "New York Times Corrections", "general"},
        {"editorial@nytimes.com", "there", "New York Times Editorial", "general"},
        {"booking@nytimes.com", "there", "New York Times Media", "general"},
        {"yann.lecun@nyu.edu", "there", "New York University", "general"},
        {"tips@npr.org", "there", "NPR", "general"},
        {"numbering@ofcom.org.uk", "there", "Ofcom", "general"},
        {"contact@ofcom.org.uk", "there", "Ofcom", "general"},
        {"corporationsecretary@ofcom.org.uk", "there", "Ofcom", "general"},
        {"ofcom.scotland@ofcom.org.uk", "there", "Ofcom", "general"},
        {"sama@openai.com", "there", "OpenAI", "general"},
        {"support@openai.com", "there", "OpenAI", "general"},
        {"hlscience@parliament.uk", "there", "Parliament Science, Innovation and Technology Committee", "general"},
        {"commonssitc@parliament.uk", "there", "Parliament Science, Innovation and Technology Committee", "general"},
        {"scitechcom@parliament.uk", "there", "Parliament Science, Innovation and Technology Committee", "general"},
        {"media@partnershiponai.org", "there", "Partnership on AI", "general"},
        {"events@partnershiponai.org", "there", "Partnership on AI", "general"},
        {"careers@partnershiponai.org", "there", "Partnership on AI", "general"},
        {"viewermail@newshour.org", "there", "PBS", "general"},
        {"pbsfoundation@pbs.org", "there", "PBS", "general"},
        {"press@pbsnc.org", "there", "PBS", "general"},
        {"tips@pcmag.com", "there", "PCMag", "general"},
        {"tips@platformer.news", "there", "Platformer", "general"},
        {"tips@politico.com", "there", "Politico", "general"},
        {"letters@popsci.com", "there", "Popular Science", "general"},
        {"hello@producthunt.com", "there", "Product Hunt", "general"},
        {"tips@propublica.org", "there", "ProPublica", "general"},
        {"tips@protocol.com", "there", "Protocol", "general"},
        {"tips@puck.news", "there", "Puck News", "general"},
        {"tips@qz.com", "there", "Quartz", "general"},
        {"media@rand.org", "there", "RAND Corporation", "general"},
        {"europeanmedia@randeurope.org", "there", "RAND Corporation", "general"},
        {"tips@recode.net", "there", "Recode", "general"},
        {"tips@restofworld.org", "there", "Rest of World", "general"},
        {"editorial.booking@thomsonreuters.com", "there", "Reuters", "general"},
        {"reutersnewsagencysales@thomsonreuters.com", "there", "Reuters", "general"},
        {"breakingviews.clientsupport@thomsonreuters.com", "there", "Reuters Breakingviews", "general"},
        {"media@samharris.org", "there", "Sam Harris", "general"},
        {"contact@samharris.org", "there", "Sam Harris", "general"},
        {"asksam@samharris.org", "there", "Sam Harris", "general"},
        {"info@samharris.org", "there", "Sam Harris", "general"},
        {"support@samharris.org", "there", "Sam Harris", "general"},
        {"editor@sciencedaily.com", "there", "Science Daily", "general"},
        {"editors@sciam.com", "there", "Scientific American", "general"},
        {"tips@semafor.com", "there", "Semafor", "general"},
        {"maurie_mueller@commerce.senate.gov", "there", "Senate Commerce Committee", "general"},
        {"melissa_braid@commerce.senate.gov", "there", "Senate Commerce Committee", "general"},
        {"peter_true@commerce.senate.gov", "there", "Senate Commerce Committee", "general"},
        {"skypress@sky.uk", "there", "Sky News", "general"},
        {"dl-trafficcopyoncall@bskyb.com", "there", "Sky News", "general"},
        {"news.tips@sky.com", "there", "Sky News", "general"},
        {"tips@slashdot.org", "there", "Slashdot", "general"},
        {"tips@slate.com", "there", "Slate", "general"},
        {"feifeili@cs.stanford.edu", "there", "Stanford University", "general"},
        {"letters@smh.com.au", "there", "Sydney Morning Herald", "general"},
        {"tips@techcrunch.com", "there", "TechCrunch", "general"},
        {"guestcolumns@techcrunch.com", "there", "TechCrunch", "general"},
        {"events@techcrunch.com", "there", "TechCrunch Events", "general"},
        {"tips@techradar.com", "there", "TechRadar", "general"},
        {"letters@theage.com.au", "there", "The Age", "general"},
        {"letters@theatlantic.com", "there", "The Atlantic", "general"},
        {"letters@economist.com", "there", "The Economist", "general"},
        {"firstperson@globeandmail.com", "there", "The Globe and Mail", "general"},
        {"education@theguardian.com", "there", "The Guardian", "general"},
        {"alan.evans@theguardian.com", "there", "The Guardian", "general"},
        {"media.enquiries@theguardian.com", "there", "The Guardian", "general"},
        {"feast@theguardian.com", "there", "The Guardian Feast", "general"},
        {"tips@thehill.com", "there", "The Hill", "general"},
        {"newsdesk@independent.co.uk", "there", "The Independent", "general"},
        {"customerservices@independent.co.uk", "there", "The Independent", "general"},
        {"beth.gordon@independent.co.uk", "there", "The Independent", "general"},
        {"letters@independent.co.uk", "there", "The Independent", "general"},
        {"tips@theinformation.com", "there", "The Information", "general"},
        {"tips@theintercept.com", "there", "The Intercept", "general"},
        {"tips@themarkup.org", "there", "The Markup", "general"},
        {"tips@thenextweb.com", "there", "The Next Web", "general"},
        {"exclusive@the-sun.co.uk", "there", "The Sun", "general"},
        {"dtletters@telegraph.co.uk", "there", "The Telegraph", "general"},
        {"investigations@telegraph.co.uk", "there", "The Telegraph", "general"},
        {"matthew.bayley@telegraph.co.uk", "there", "The Telegraph", "general"},
        {"care@thetimes.com", "there", "The Times", "general"},
        {"home.news@thetimes.co.uk", "there", "The Times", "general"},
        {"interview.requests@thetimes.co.uk", "there", "The Times", "general"},
        {"letters@thetimes.co.uk", "there", "The Times UK", "general"},
        {"tips@theverge.com", "there", "The Verge", "general"},
        {"techpitches@theverge.com", "there", "The Verge", "general"},
        {"aude.white@voxmedia.com", "there", "The Verge", "general"},
        {"mediarelations@thomsonreuters.com", "there", "Thomson Reuters", "general"},
        {"gehna.singhkareckas@thomsonreuters.com", "there", "Thomson Reuters", "general"},
        {"tips@tomsguide.com", "there", "Tom's Guide", "general"},
        {"city@thestar.ca", "there", "Toronto Star", "general"},
        {"lettertoed@thestar.ca", "there", "Toronto Star", "general"},
        {"oped@thestar.ca", "there", "Toronto Star", "general"},
        {"papressduty@state.gov", "there", "U.S. Department of State", "general"},
        {"evaluationpolicyforeignassistance@state.gov", "there", "U.S. Department of State", "general"},
        {"geoffrey.hinton@gmail.com", "there", "University of Toronto", "general"},
        {"tips@venturebeat.com", "there", "VentureBeat", "general"},
        {"sales@venturebeat.com", "there", "VentureBeat", "general"},
        {"events@venturebeat.com", "there", "VentureBeat", "general"},
        {"tips@vox.com", "there", "Vox", "general"},
        {"wsj.ltrs@wsj.com", "there", "Wall Street Journal", "general"},
        {"letters@washpost.com", "there", "Washington Post Letters", "general"},
        {"lockbox@washpost.com", "there", "Washington Post Tips", "general"},
        {"whiaanhpi@hhs.gov", "there", "White House Initiative on Asian Americans, Native Hawaiians, and Pacific Islanders", "general"},
        {"engagement@ostp.eop.gov", "there", "White House Office of Science and Technology Policy (OSTP)", "general"},
        {"scheduling@ostp.eop.gov", "there", "White House Office of Science and Technology Policy (OSTP)", "general"},
        {"information@ostp.eop.gov", "there", "White House Office of Science and Technology Policy (OSTP)", "general"},
        {"ostpfoia@ostp.eop.gov", "there", "White House Office of Science and Technology Policy (OSTP)", "general"},
        {"ai-strategy@ostp.eop.gov", "there", "White House Office of Science and Technology Policy (OSTP)", "general"},
        {"press@wired.com", "there", "Wired", "general"},
        {"mail@wired.com", "there", "Wired", "general"},
        {"press@wired.co.uk", "there", "Wired UK", "general"},
        {"market@xinhuainfolink.com", "there", "Xinhua InfoLink", "general"},
        {"xinhuanet_english@news.cn", "there", "Xinhua News Agency", "general"},
        {"info@xhnmedia.com", "there", "Xinhua News Media Holdings Limited", "general"},
        {"david@zdnet.com", "there", "ZDNet", "general"},
        {"tips@zdnet.com", "there", "ZDNet", "general"},
        {"tips@appleinsider.com", "there", "AppleInsider", "general"},
        {"press@15five.com", "there", "15Five AI", "general"},
        {"3blue1brown@gmail.com", "there", "3Blue1Brown", "general"},
        {"press@6sense.com", "there", "6sense AI", "general"},
        {"ai@a16z.com", "there", "a16z AI", "general"},
        {"press@a16z.com", "there", "a16z Press", "general"},
        {"press@aaai.org", "there", "AAAI", "general"},
        {"press@helloabound.com", "there", "Abound AI", "general"},
        {"ai@accel.com", "there", "Accel AI", "general"},
        {"press@achievers.com", "there", "Achievers AI", "general"},
        {"press@aclweb.org", "there", "ACL", "general"},
        {"press@adept.ai", "there", "Adept AI Press", "general"},
        {"press@adobe.com", "there", "Adobe AI", "general"},
        {"info@aibusiness.com", "there", "AI Business", "general"},
        {"info@ai.vc", "there", "AI Capital", "general"},
        {"aicoffeebreak@gmail.com", "there", "AI Coffee Break", "general"},
        {"contact@aiethicslab.com", "there", "AI Ethics Lab", "general"},
        {"aiexplained@gmail.com", "there", "AI Explained", "general"},
        {"editorial@artificialintelligence-news.com", "there", "AI News", "general"},
        {"aipodcast@nvidia.com", "there", "AI Podcast NVIDIA", "general"},
        {"info@caidp.org", "there", "AI Policy Center", "general"},
        {"info@theaisummit.com", "there", "AI Summit", "general"},
        {"michael@ai-supremacy.com", "there", "AI Supremacy", "general"},
        {"contact@aitimejournal.com", "there", "AI Time Journal", "general"},
        {"info@aiworld.com", "there", "AI World", "general"},
        {"press@cohere.com", "there", "Aidan Gomez", "general"},
        {"press@airgram.io", "there", "Airgram", "general"},
        {"press@airtable.com", "there", "Airtable AI", "general"},
        {"media@turing.ac.uk", "there", "Alan Turing Institute", "general"},
        {"press@ajl.org", "there", "Algorithmic Justice League", "general"},
        {"press@alibaba.com", "there", "Alibaba AI", "general"},
        {"hello@alltechishuman.org", "there", "All Tech Is Human", "general"},
        {"press@allenai.org", "there", "Allen AI", "general"},
        {"allie@alliekmiller.com", "there", "Allie K. Miller", "general"},
        {"ally-press@microsoft.com", "there", "Ally.io AI", "general"},
        {"lior@alphasignal.ai", "there", "AlphaSignal", "general"},
        {"press@alyce.com", "there", "Alyce AI", "general"},
        {"aws-ai-pr@amazon.com", "there", "Amazon AI", "general"},
        {"codewhisperer-press@amazon.com", "there", "Amazon CodeWhisperer", "general"},
        {"editorial@analyticsindiamag.com", "there", "Analytics India Magazine", "general"},
        {"karpathy@gmail.com", "there", "Andrej Karpathy", "general"},
        {"andrew@deeplearning.ai", "there", "Andrew Ng", "general"},
        {"contact@deeplearning.ai", "there", "Andrew Ng", "general"},
        {"press@ankorstore.com", "there", "Ankorstore AI", "general"},
        {"press@anyscale.com", "there", "Anyscale", "general"},
        {"press@aopplus.com", "there", "AOP+ AI", "general"},
        {"press@apify.com", "there", "Apify", "general"},
        {"press@apliiq.com", "there", "Apliiq AI", "general"},
        {"press@apollo.io", "there", "Apollo AI", "general"},
        {"press@appen.com", "there", "Appen", "general"},
        {"press@arize.com", "there", "Arize AI", "general"},
        {"tips@arstechnica.com", "there", "Ars Technica Tips", "general"},
        {"press@mistral.ai", "there", "Arthur Mensch", "general"},
        {"arxivinsights@gmail.com", "there", "Arxiv Insights", "general"},
        {"press@asana.com", "there", "Asana AI", "general"},
        {"press@augmentcode.com", "there", "Augment Code", "general"},
        {"press@autodesk.com", "there", "Autodesk AI", "general"},
        {"press@avoma.com", "there", "Avoma", "general"},
        {"press@awardco.com", "there", "Awardco AI", "general"},
        {"press@awkwardstyles.com", "there", "Awkward Styles AI", "general"},
        {"press@baseten.co", "there", "Baseten", "general"},
        {"press@basic.ai", "there", "BasicAI", "general"},
        {"ben@bensbites.co", "there", "Ben's Bites", "general"},
        {"benj.edwards@arstechnica.com", "there", "Benj Edwards", "general"},
        {"press@bentoml.com", "there", "BentoML", "general"},
        {"bair@berkeley.edu", "there", "Berkeley AI Research", "general"},
        {"bernard@bernardmarr.com", "there", "Bernard Marr", "general"},
        {"ai@bvp.com", "there", "Bessemer AI", "general"},
        {"press@betterworks.com", "there", "Betterworks AI", "general"},
        {"press@blueboard.com", "there", "Blueboard AI", "general"},
        {"press@bonus.ly", "there", "Bonusly AI", "general"},
        {"press@brandboom.com", "there", "Brandboom AI", "general"},
        {"press@brave.com", "there", "Brave AI", "general"},
        {"press@brex.com", "there", "Brex AI", "general"},
        {"press@browserbase.com", "there", "Browserbase", "general"},
        {"press@bulletin.co", "there", "Bulletin AI", "general"},
        {"press@c3.ai", "there", "C3.ai", "general"},
        {"cade.metz@nytimes.com", "there", "Cade Metz", "general"},
        {"media@safe.ai", "there", "CAIS Press", "general"},
        {"ai-media@cam.ac.uk", "there", "Cambridge AI", "general"},
        {"press@canva.com", "there", "Canva AI", "general"},
        {"carl.franzen@venturebeat.com", "there", "Carl Franzen", "general"},
        {"press@caroo.com", "there", "Caroo AI", "general"},
        {"press@carta.com", "there", "Carta AI", "general"},
        {"cassie@kozyrkov.com", "there", "Cassie Kozyrkov", "general"},
        {"press@cerebras.net", "there", "Cerebras", "general"},
        {"press@character.ai", "there", "Character AI", "general"},
        {"chorus-press@zoominfo.com", "there", "Chorus AI", "general"},
        {"press@trychroma.com", "there", "Chroma", "general"},
        {"press@clari.com", "there", "Clari AI", "general"},
        {"press@clarifai.com", "there", "Clarifai", "general"},
        {"claude@anthropic.com", "there", "Claude Anthropic", "general"},
        {"clearbit-press@hubspot.com", "there", "Clearbit AI", "general"},
        {"clem@huggingface.co", "there", "Clem Delangue", "general"},
        {"press@clickup.com", "there", "ClickUp AI", "general"},
        {"ai-media@cs.cmu.edu", "there", "CMU AI", "general"},
        {"ai@coatue.com", "there", "Coatue AI", "general"},
        {"press@coda.io", "there", "Coda AI", "general"},
        {"press@codeium.com", "there", "Codeium", "general"},
        {"press@cognition-labs.com", "there", "Cognition Labs", "general"},
        {"press@thecommons.earth", "there", "Commons AI", "general"},
        {"contact@conjecture.dev", "there", "Connor Leahy", "general"},
        {"press@copy.ai", "there", "Copy.ai", "general"},
        {"press@craft.do", "there", "Craft AI", "general"},
        {"press@creoate.com", "there", "Creoate AI", "general"},
        {"press@cultureamp.com", "there", "Culture Amp AI", "general"},
        {"press@cursor.sh", "there", "Cursor AI", "general"},
        {"press@customcat.com", "there", "CustomCat AI", "general"},
        {"press@cvpr.org", "there", "CVPR", "general"},
        {"contact@dairinstitute.org", "there", "DAIR Institute", "general"},
        {"dan@safe.ai", "there", "Dan Hendrycks", "general"},
        {"rus@csail.mit.edu", "there", "Daniela Rus", "general"},
        {"press@anthropic.com", "there", "Dario Amodei", "general"},
        {"editor@datasciencecentral.com", "there", "Data Science Central", "general"},
        {"ai-press@databricks.com", "there", "Databricks AI", "general"},
        {"press@dataiku.com", "there", "Dataiku", "general"},
        {"press@datarobot.com", "there", "DataRobot", "general"},
        {"dalba@bloomberg.net", "there", "Davey Alba", "general"},
        {"press@deel.com", "there", "Deel AI", "general"},
        {"press@demandbase.com", "there", "Demandbase AI", "general"},
        {"press@deepmind.com", "there", "Demis Hassabis", "general"},
        {"press@descript.com", "there", "Descript AI", "general"},
        {"press@determined.ai", "there", "Determined AI", "general"},
        {"devin.coldewey@techcrunch.com", "there", "Devin Coldewey", "general"},
        {"press@dhgate.com", "there", "DHgate AI", "general"},
        {"press@diffgram.com", "there", "Diffgram", "general"},
        {"press@doba.com", "there", "Doba AI", "general"},
        {"drift-press@salesloft.com", "there", "Drift AI", "general"},
        {"press@dripshipper.com", "there", "Dripshipper AI", "general"},
        {"press@duckduckgo.com", "there", "DuckDuckGo AI", "general"},
        {"press@ec21.com", "there", "EC21 AI", "general"},
        {"press@ecvv.com", "there", "ECVV AI", "general"},
        {"informatics-media@ed.ac.uk", "there", "Edinburgh AI", "general"},
        {"press@effy.ai", "there", "Effy AI", "general"},
        {"contact@eleuther.ai", "there", "EleutherAI", "general"},
        {"press@elevenlabs.io", "there", "ElevenLabs", "general"},
        {"contact@intelligence.org", "there", "Eliezer Yudkowsky", "general"},
        {"press@stability.ai", "there", "Emad Mostaque", "general"},
        {"emilia.david@venturebeat.com", "there", "Emilia David", "general"},
        {"press@encord.com", "there", "Encord", "general"},
        {"press@engagedly.com", "there", "Engagedly AI", "general"},
        {"ai-media@epfl.ch", "there", "EPFL AI", "general"},
        {"press@esources.co.uk", "there", "Esources AI", "general"},
        {"ai-media@ethz.ch", "there", "ETH Zurich AI", "general"},
        {"press@europages.com", "there", "Europages AI", "general"},
        {"press@eworldtrade.com", "there", "eWorldTrade AI", "general"},
        {"press@exa.ai", "there", "Exa AI", "general"},
        {"press@exporthub.com", "there", "ExportHub AI", "general"},
        {"eyeonai@gmail.com", "there", "Eye on AI Podcast", "general"},
        {"press@faire.com", "there", "Faire AI", "general"},
        {"press@fashinza.com", "there", "Fashinza AI", "general"},
        {"press@fashion.cloud", "there", "Fashion Cloud AI", "general"},
        {"press@fathom.video", "there", "Fathom AI", "general"},
        {"press@fellow.app", "there", "Fellow AI", "general"},
        {"press@fiddler.ai", "there", "Fiddler AI", "general"},
        {"press@figma.com", "there", "Figma AI", "general"},
        {"press@fireflies.ai", "there", "Fireflies AI", "general"},
        {"press@fond.co", "there", "Fond AI", "general"},
        {"press@freshworks.com", "there", "Freshdesk AI", "general"},
        {"press@fuel.me", "there", "Fuel AI", "general"},
        {"press@gelato.com", "there", "Gelato AI", "general"},
        {"gemini-press@google.com", "there", "Gemini Google", "general"},
        {"ai@generalcatalyst.com", "there", "General Catalyst AI", "general"},
        {"hinton@cs.toronto.edu", "there", "Geoffrey Hinton", "general"},
        {"press@giftagram.com", "there", "Giftagram AI", "general"},
        {"press@github.com", "there", "GitHub Copilot", "general"},
        {"press@globalsources.com", "there", "Global Sources AI", "general"},
        {"press@go4worldbusiness.com", "there", "Go4WorldBusiness AI", "general"},
        {"press@gong.io", "there", "Gong AI", "general"},
        {"research-press@google.com", "there", "Google AI Research", "general"},
        {"gemini-code-press@google.com", "there", "Google Gemini Code", "general"},
        {"meet-press@google.com", "there", "Google Meet AI", "general"},
        {"press@gooten.com", "there", "Gooten AI", "general"},
        {"podcast@wandb.com", "there", "Gradient Dissent", "general"},
        {"press@grain.com", "there", "Grain AI", "general"},
        {"press@grammarly.com", "there", "Grammarly AI", "general"},
        {"press@graphcore.ai", "there", "Graphcore", "general"},
        {"ai@greylock.com", "there", "Greylock AI", "general"},
        {"press@groq.com", "there", "Groq", "general"},
        {"press@quantive.com", "there", "Gtmhub AI", "general"},
        {"press@gusto.com", "there", "Gusto AI", "general"},
        {"press@h2o.ai", "there", "H2O.ai", "general"},
        {"press@handshake.com", "there", "Handshake AI", "general"},
        {"press@hasty.ai", "there", "Hasty AI", "general"},
        {"hayden.field@voxmedia.com", "there", "Hayden Field", "general"},
        {"press@deepset.ai", "there", "Haystack", "general"},
        {"press@heartex.com", "there", "Heartex", "general"},
        {"press@height.app", "there", "Height AI", "general"},
        {"press@hirebook.com", "there", "Hirebook AI", "general"},
        {"press@hktdc.com", "there", "HKTDC AI", "general"},
        {"press@hubba.com", "there", "Hubba AI", "general"},
        {"press@hubspot.com", "there", "HubSpot AI", "general"},
        {"press@huggingface.co", "there", "Hugging Face Press", "general"},
        {"press@humane.com", "there", "Humane AI", "general"},
        {"aipress@us.ibm.com", "there", "IBM AI", "general"},
        {"press@iclr.cc", "there", "ICLR", "general"},
        {"press@icml.cc", "there", "ICML", "general"},
        {"press@ijcai.org", "there", "IJCAI", "general"},
        {"info@ssi.inc", "there", "Ilya Sutskever", "general"},
        {"ai-press@imperial.ac.uk", "there", "Imperial AI", "general"},
        {"importai@substack.com", "there", "Import AI", "general"},
        {"ai@indexventures.com", "there", "Index Ventures AI", "general"},
        {"press@indiamart.com", "there", "IndiaMART AI", "general"},
        {"press@inflection.ai", "there", "Inflection AI", "general"},
        {"press@inkedjoy.com", "there", "Inkedjoy AI", "general"},
        {"presse@inria.fr", "there", "INRIA AI", "general"},
        {"press@intercom.com", "there", "Intercom AI", "general"},
        {"press@intuit.com", "there", "Intuit AI", "general"},
        {"press@inventorysource.com", "there", "Inventory Source AI", "general"},
        {"jack@jack-clark.net", "there", "Jack Clark", "general"},
        {"james.vincent@theverge.com", "there", "James Vincent", "general"},
        {"jan@anthropic.com", "there", "Jan Leike", "general"},
        {"press@jasper.ai", "there", "Jasper AI", "general"},
        {"jeremy@fast.ai", "there", "Jeremy Howard", "general"},
        {"press@jetprint.io", "there", "JetPrint AI", "general"},
        {"press@atlassian.com", "there", "Jira AI", "general"},
        {"jon@jonkrohn.com", "there", "Jon Krohn", "general"},
        {"press@joor.com", "there", "Joor AI", "general"},
        {"info@ajl.org", "there", "Joy Buolamwini", "general"},
        {"press@kagi.com", "there", "Kagi AI", "general"},
        {"ai-media@kaist.ac.kr", "there", "KAIST AI", "general"},
        {"karen@theatlantic.com", "there", "Karen Hao", "general"},
        {"press@worktango.com", "there", "Kazoo AI", "general"},
        {"editor@kdnuggets.com", "there", "KDnuggets", "general"},
        {"ai@khoslaventures.com", "there", "Khosla Ventures AI", "general"},
        {"press@kili-technology.com", "there", "Kili Technology", "general"},
        {"kirk.borne@gmail.com", "there", "Kirk Borne", "general"},
        {"press@koan.co", "there", "Koan AI", "general"},
        {"press@kompass.com", "there", "Kompass AI", "general"},
        {"press@krisp.ai", "there", "Krisp AI", "general"},
        {"press@kudos.com", "there", "Kudos AI", "general"},
        {"kyle.wiggers@techcrunch.com", "there", "Kyle Wiggers", "general"},
        {"press@labelbox.com", "there", "Labelbox", "general"},
        {"press@labellerr.com", "there", "Labellerr", "general"},
        {"press@landing.ai", "there", "Landing AI", "general"},
        {"press@langchain.dev", "there", "LangChain", "general"},
        {"press@lattice.com", "there", "Lattice AI", "general"},
        {"press@lenewblack.com", "there", "Le New Black AI", "general"},
        {"press@leapsome.com", "there", "Leapsome AI", "general"},
        {"press@lightly.ai", "there", "Lightly AI", "general"},
        {"ai@lsvp.com", "there", "Lightspeed AI", "general"},
        {"press@limitless.ai", "there", "Limitless AI", "general"},
        {"press@linear.app", "there", "Linear AI", "general"},
        {"press@llamaindex.ai", "there", "LlamaIndex", "general"},
        {"press@loom.com", "there", "Loom AI", "general"},
        {"press@loopandtie.com", "there", "Loop & Tie AI", "general"},
        {"lukas@wandb.com", "there", "Lukas Biewald", "general"},
        {"press@meetmable.com", "there", "Mable AI", "general"},
        {"jason@machinelearningmastery.com", "there", "Machine Learning Mastery", "general"},
        {"phil@mlwithphil.com", "there", "Machine Learning with Phil", "general"},
        {"press@made-in-china.com", "there", "Made-in-China AI", "general"},
        {"madhumita.murgia@ft.com", "there", "Madhumita Murgia", "general"},
        {"press@magic.dev", "there", "Magic AI", "general"},
        {"press@makersrow.com", "there", "Maker's Row AI", "general"},
        {"presse@tuebingen.mpg.de", "there", "Max Planck AI", "general"},
        {"tegmark@mit.edu", "there", "Max Tegmark", "general"},
        {"press@megagoods.com", "there", "Megagoods AI", "general"},
        {"melissa.heikkila@technologyreview.com", "there", "Melissa Heikkila", "general"},
        {"press@mem.ai", "there", "Mem AI", "general"},
        {"press@mercury.com", "there", "Mercury AI", "general"},
        {"press@mesh.ai", "there", "Mesh AI", "general"},
        {"ai-press@meta.com", "there", "Meta AI", "general"},
        {"fair-press@meta.com", "there", "Meta AI Research", "general"},
        {"michael.nunez@venturebeat.com", "there", "Michael Nuñez", "general"},
        {"aipress@microsoft.com", "there", "Microsoft AI", "general"},
        {"msrpress@microsoft.com", "there", "Microsoft Research AI", "general"},
        {"press@midjourney.com", "there", "Midjourney", "general"},
        {"communications@mila.quebec", "there", "Mila Quebec", "general"},
        {"csail-media@mit.edu", "there", "MIT CSAIL", "general"},
        {"mlflow@databricks.com", "there", "MLflow", "general"},
        {"contact@mlst.ai", "there", "MLST Podcast", "general"},
        {"press@modal.com", "there", "Modal", "general"},
        {"press@modalyst.co", "there", "Modalyst AI", "general"},
        {"press@monday.com", "there", "Monday AI", "general"},
        {"contact@montrealethics.ai", "there", "Montreal AI Ethics", "general"},
        {"press@mooncamp.com", "there", "Mooncamp AI", "general"},
        {"press@mosaicml.com", "there", "Mosaic ML", "general"},
        {"press@motivosity.com", "there", "Motivosity AI", "general"},
        {"press@mtmrecognition.com", "there", "MTM Recognition AI", "general"},
        {"press@multion.ai", "there", "Multion", "general"},
        {"press@nationaldropshippers.com", "there", "National Dropshippers AI", "general"},
        {"ai@nea.com", "there", "NEA AI", "general"},
        {"press@nectarhr.com", "there", "Nectar AI", "general"},
        {"neeva-press@snowflake.com", "there", "Neeva AI", "general"},
        {"press@neurips.cc", "there", "NeurIPS", "general"},
        {"nick.bostrom@philosophy.ox.ac.uk", "there", "Nick Bostrom", "general"},
        {"nitasha.tiku@washpost.com", "there", "Nitasha Tiku", "general"},
        {"noelle@aileadershipinstitute.com", "there", "Noelle Russell", "general"},
        {"press@notion.so", "there", "Notion AI", "general"},
        {"press@notta.ai", "there", "Notta AI", "general"},
        {"press@nuorder.com", "there", "NuORDER AI", "general"},
        {"ai-media@nus.edu.sg", "there", "NUS AI", "general"},
        {"aipress@nvidia.com", "there", "NVIDIA AI", "general"},
        {"press@octanner.com", "there", "O.C. Tanner AI", "general"},
        {"safety@openai.com", "there", "OpenAI Safety", "general"},
        {"press@oracle.com", "there", "Oracle AI", "general"},
        {"press@orderchamp.com", "there", "Orderchamp AI", "general"},
        {"press@ordre.com", "there", "Ordre AI", "general"},
        {"press@outreach.io", "there", "Outreach AI", "general"},
        {"ai-comms@cs.ox.ac.uk", "there", "Oxford AI", "general"},
        {"press@oysterhr.com", "there", "Oyster AI", "general"},
        {"press@palantir.com", "there", "Palantir AI", "general"},
        {"polson@bloomberg.net", "there", "Parmy Olson", "general"},
        {"pascal@pascalbornet.com", "there", "Pascal Bornet", "general"},
        {"press@paypal.com", "there", "PayPal AI", "general"},
        {"ai-media@pku.edu.cn", "there", "Peking AI", "general"},
        {"press@peoplebox.ai", "there", "Peoplebox AI", "general"},
        {"press@perdoo.com", "there", "Perdoo AI", "general"},
        {"press@perplexity.ai", "there", "Perplexity AI", "general"},
        {"press@pfl.com", "there", "PFL AI", "general"},
        {"press@phind.com", "there", "Phind", "general"},
        {"press@pietrastudio.com", "there", "Pietra AI", "general"},
        {"press@pika.art", "there", "Pika Labs", "general"},
        {"press@pillowprofits.com", "there", "Pillow Profits AI", "general"},
        {"press@pinecone.io", "there", "Pinecone", "general"},
        {"press@plaid.com", "there", "Plaid AI", "general"},
        {"press@podfoods.co", "there", "Pod Foods AI", "general"},
        {"press@poolside.ai", "there", "Poolside AI", "general"},
        {"press@postal.io", "there", "Postal AI", "general"},
        {"practicalai@changelog.com", "there", "Practical AI Podcast", "general"},
        {"press@printfection.com", "there", "Printfection AI", "general"},
        {"press@printful.com", "there", "Printful AI", "general"},
        {"press@prodigi.com", "there", "Prodigi AI", "general"},
        {"press@profit.co", "there", "Profit.co AI", "general"},
        {"press@rabbit.tech", "there", "Rabbit AI", "general"},
        {"rmetz@bloomberg.net", "there", "Rachel Metz", "general"},
        {"rachel@fast.ai", "there", "Rachel Thomas", "general"},
        {"press@ramp.com", "there", "Ramp AI", "general"},
        {"press@rangeme.com", "there", "RangeMe AI", "general"},
        {"press@reachdesk.com", "there", "Reachdesk AI", "general"},
        {"press@reflect.app", "there", "Reflect AI", "general"},
        {"press@reflektive.com", "there", "Reflektive AI", "general"},
        {"press@remote.com", "there", "Remote AI", "general"},
        {"press@replicate.com", "there", "Replicate", "general"},
        {"press@replika.ai", "there", "Replika", "general"},
        {"press@replit.com", "there", "Replit AI", "general"},
        {"press@rewind.ai", "there", "Rewind AI", "general"},
        {"richard.waters@ft.com", "there", "Richard Waters", "general"},
        {"press@rippling.com", "there", "Rippling AI", "general"},
        {"press@roboflow.com", "there", "Roboflow", "general"},
        {"press@runwayml.com", "there", "Runway ML", "general"},
        {"press@salehoo.com", "there", "SaleHoo AI", "general"},
        {"press@salesforce.com", "there", "Salesforce AI", "general"},
        {"press@salesloft.com", "there", "Salesloft AI", "general"},
        {"press@openai.com", "there", "Sam Altman", "general"},
        {"sam@twimlai.com", "there", "Sam Charrington", "general"},
        {"press@sama.com", "there", "Sama", "general"},
        {"press@sambanova.ai", "there", "SambaNova", "general"},
        {"press@sap.com", "there", "SAP AI", "general"},
        {"press@scalablepress.com", "there", "Scalable Press AI", "general"},
        {"press@scale.com", "there", "Scale AI Press", "general"},
        {"press@seldon.io", "there", "Seldon", "general"},
        {"press@sendoso.com", "there", "Sendoso AI", "general"},
        {"harrison@pythonprogramming.net", "there", "Sentdex", "general"},
        {"ai@sequoiacap.com", "there", "Sequoia AI", "general"},
        {"press@serpapi.com", "there", "SerpAPI", "general"},
        {"press@servicenow.com", "there", "ServiceNow AI", "general"},
        {"press@sewport.com", "there", "Sewport AI", "general"},
        {"sharon.goldman@venturebeat.com", "there", "Sharon Goldman", "general"},
        {"press@shirtee.com", "there", "Shirtee AI", "general"},
        {"press@shopify.com", "there", "Shopify AI", "general"},
        {"press@shortcut.com", "there", "Shortcut AI", "general"},
        {"siraj@sirajraval.com", "there", "Siraj Raval", "general"},
        {"slack-press@salesforce.com", "there", "Slack AI", "general"},
        {"press@snacknation.com", "there", "SnackNation AI", "general"},
        {"press@snappy.com", "there", "Snappy AI", "general"},
        {"press@snorkel.ai", "there", "Snorkel AI", "general"},
        {"ai-press@snowflake.com", "there", "Snowflake AI", "general"},
        {"sora@openai.com", "there", "Sora OpenAI", "general"},
        {"press@sourcegraph.com", "there", "Sourcegraph", "general"},
        {"press@sourcify.com", "there", "Sourcify AI", "general"},
        {"ai@sparkcapital.com", "there", "Spark Capital AI", "general"},
        {"press@spocket.co", "there", "Spocket AI", "general"},
        {"press@spod.com", "there", "SPOD AI", "general"},
        {"press@spokecustom.com", "there", "SPOKE Custom AI", "general"},
        {"press@sqetch.co", "there", "Sqetch AI", "general"},
        {"press@block.xyz", "there", "Square AI", "general"},
        {"hai-communications@stanford.edu", "there", "Stanford HAI", "general"},
        {"hai-press@stanford.edu", "there", "Stanford HAI Press", "general"},
        {"josh@statquest.org", "there", "StatQuest", "general"},
        {"steve@ai4diversity.com", "there", "Steve Nouri", "general"},
        {"press@stripe.com", "there", "Stripe AI", "general"},
        {"russell@cs.berkeley.edu", "there", "Stuart Russell", "general"},
        {"press@subliminator.com", "there", "Subliminator AI", "general"},
        {"press@sunrisewholesalemerchandise.com", "there", "Sunrise Wholesale AI", "general"},
        {"press@superannotate.com", "there", "SuperAnnotate", "general"},
        {"zain@superhuman.ai", "there", "Superhuman AI", "general"},
        {"press@surgehq.ai", "there", "Surge AI", "general"},
        {"press@swag.com", "there", "Swag.com AI", "general"},
        {"press@swagup.com", "there", "SwagUp AI", "general"},
        {"editor@syncedreview.com", "there", "Synced Review", "general"},
        {"press@syncee.com", "there", "Syncee AI", "general"},
        {"press@synthesia.io", "there", "Synthesia", "general"},
        {"press@t-pop.fr", "there", "T-Pop AI", "general"},
        {"press@tabnine.com", "there", "Tabnine", "general"},
        {"press@tana.inc", "there", "Tana AI", "general"},
        {"press@taskade.com", "there", "Taskade AI", "general"},
        {"press@tavily.com", "there", "Tavily", "general"},
        {"teams-press@microsoft.com", "there", "Teams AI", "general"},
        {"press@techpacker.com", "there", "Techpacker AI", "general"},
        {"press@teelaunch.com", "there", "Teelaunch AI", "general"},
        {"press@terryberry.com", "there", "Terryberry AI", "general"},
        {"editor@theaijournal.com", "there", "The AI Journal", "general"},
        {"thebatch@deeplearning.ai", "there", "The Batch", "general"},
        {"pete@theneurondaily.com", "there", "The Neuron", "general"},
        {"rowan@therundown.ai", "there", "The Rundown AI", "general"},
        {"press@thnks.com", "there", "Thnks AI", "general"},
        {"thomas@huggingface.co", "there", "Thomas Wolf", "general"},
        {"press@thomasnet.com", "there", "ThomasNet AI", "general"},
        {"ai@tigerglobal.com", "there", "Tiger Global AI", "general"},
        {"tim@mlst.ai", "there", "Tim Scarfe", "general"},
        {"timnit@dairinstitute.org", "there", "Timnit Gebru", "general"},
        {"press@tldv.io", "there", "tl;dv", "general"},
        {"ai@tldr.tech", "there", "TLDR AI", "general"},
        {"press@together.ai", "there", "Together AI", "general"},
        {"ai-media@u-tokyo.ac.jp", "there", "Tokyo AI", "general"},
        {"press@toloka.ai", "there", "Toloka", "general"},
        {"press@tome.app", "there", "Tome AI", "general"},
        {"press@toptenwholesale.com", "there", "TopTenWholesale AI", "general"},
        {"tds.team@medium.com", "there", "Towards Data Science", "general"},
        {"press@tradeindia.com", "there", "TradeIndia AI", "general"},
        {"press@tradekey.com", "there", "TradeKey AI", "general"},
        {"ai-media@tsinghua.edu.cn", "there", "Tsinghua AI", "general"},
        {"press@tundra.com", "there", "Tundra AI", "general"},
        {"press@turing.com", "there", "Turing AI", "general"},
        {"podcast@twimlai.com", "there", "TWIML Podcast", "general"},
        {"karoly@twominutepapers.com", "there", "Two Minute Papers", "general"},
        {"ai-media@ucl.ac.uk", "there", "UCL AI", "general"},
        {"contact@unite.ai", "there", "Unite.AI", "general"},
        {"press@unstructured.io", "there", "Unstructured", "general"},
        {"press@v7labs.com", "there", "V7 Labs", "general"},
        {"communications@vectorinstitute.ai", "there", "Vector Institute", "general"},
        {"vin@vsquared.org", "there", "Vin Vashishta", "general"},
        {"press@weaviate.io", "there", "Weaviate", "general"},
        {"webex-press@cisco.com", "there", "Webex AI", "general"},
        {"press@weekdone.com", "there", "Weekdone AI", "general"},
        {"press@wandb.com", "there", "Weights & Biases", "general"},
        {"press@wholesalecentral.com", "there", "Wholesale Central AI", "general"},
        {"press@wholesale2b.com", "there", "Wholesale2B AI", "general"},
        {"press@whylabs.ai", "there", "WhyLabs", "general"},
        {"will.douglas.heaven@technologyreview.com", "there", "Will Douglas Heaven", "general"},
        {"will.knight@wired.com", "there", "Will Knight", "general"},
        {"press@workboard.com", "there", "Workboard AI", "general"},
        {"press@workday.com", "there", "Workday AI", "general"},
        {"press@workhuman.com", "there", "Workhuman AI", "general"},
        {"info@worldsummit.ai", "there", "World AI Summit", "general"},
        {"press@worldwidebrands.com", "there", "Worldwide Brands AI", "general"},
        {"press@writer.com", "there", "Writer AI", "general"},
        {"yann@cs.nyu.edu", "there", "Yann LeCun", "general"},
        {"yannic@kilcher.ch", "there", "Yannic Kilcher", "general"},
        {"press@you.com", "there", "You.com", "general"},
        {"press@zendesk.com", "there", "Zendesk AI", "general"},
        {"press@zilingo.com", "there", "Zilingo AI", "general"},
        {"press@zoom.us", "there", "Zoom AI", "general"},
        {"press@zoominfo.com", "there", "ZoomInfo AI", "general"},
        {"news@techcrunch.com", "there", "your publication", "general"},
        {"tips@wired.com", "there", "your publication", "general"},
        {"tips@bloomberg.com", "there", "your publication", "general"},
        {"tips@reuters.com", "there", "your publication", "general"},
        {"tips@forbes.com", "there", "your publication", "general"},
        {"tips@geekwire.com", "there", "your publication", "general"},
        {"tips@wsj.com", "there", "your publication", "general"},
        {"tips@ft.com", "there", "your publication", "general"},
        {"tips@theguardian.com", "there", "your publication", "general"},
        {"tips@nytimes.com", "there", "your publication", "general"},
        {"tips@washingtonpost.com", "there", "your publication", "general"},
        {"tips@cnbc.com", "there", "your publication", "general"},
        {"tips@bbc.com", "there", "your publication", "general"},
        {"tips@apnews.com", "there", "your publication", "general"},
        {"tips@ycombinator.com", "there", "your publication", "general"},
        {"tips@nature.com", "there", "your publication", "general"},
        {"tips@sciencedaily.com", "there", "your publication", "general"},
        {"tips@aibusiness.com", "there", "your publication", "general"},
        {"tips@roboticsbusinessreview.com", "there", "your publication", "general"},
        {"tips@govtech.com", "there", "your publication", "general"},
        {"tips@nextgov.com", "there", "your publication", "general"},
        {"tips@infoq.com", "there", "your publication", "general"},
        {"tips@dzone.com", "there", "your publication", "general"},
        {"tips@producthunt.com", "there", "your publication", "general"},
        {"tips@angellist.com", "there", "your publication", "general"},
        {"press@ice.com", "there", "your publication", "general"},
        {"press@kpmg.com", "there", "your publication", "general"},
        {"yann@meta.com", "there", "your publication", "general"},
        {"press@reddit.com", "there", "your publication", "general"},
        {"contact@aiindex.stanford.edu", "there", "your publication", "general"},
        {"press@isde.canada.ca", "there", "your publication", "general"},
        {"press@bofa.com", "there", "your publication", "general"},
        {"press@forrester.com", "there", "your publication", "general"},
        {"commissioner@ftc.gov", "there", "your publication", "general"},
        {"pg@ycombinator.com", "there", "your publication", "general"},
        {"press@csa.ca", "there", "your publication", "general"},
        {"tech@seattletimes.com", "there", "your publication", "general"},
        {"press@cmu.edu", "there", "your publication", "general"},
        {"press@google.com", "there", "your publication", "general"},
        {"tech@msnbc.com", "there", "your publication", "general"},
        {"press@aisummit.com", "there", "your publication", "general"},
        {"press@fidelity.com", "there", "your publication", "general"},
        {"press@skillshare.com", "there", "your publication", "general"},
        {"tech@nationalpost.com", "there", "your publication", "general"},
        {"press@clearco.com", "there", "your publication", "general"},
        {"press@udacity.com", "there", "your publication", "general"},
        {"tech@edmontonjournal.com", "there", "your publication", "general"},
        {"jensen@nvidia.com", "there", "your publication", "general"},
        {"press@canada.ca", "there", "your publication", "general"},
        {"ginni@ibm.com", "there", "your publication", "general"},
        {"tech@globalnews.ca", "there", "your publication", "general"},
        {"safra@oracle.com", "there", "your publication", "general"},
        {"press@nuvei.com", "there", "your publication", "general"},
        {"press@conferenceboard.ca", "there", "your publication", "general"},
        {"satya@microsoft.com", "there", "your publication", "general"},
        {"press@gs.com", "there", "your publication", "general"},
        {"press@blackrock.com", "there", "your publication", "general"},
        {"press@duolingo.com", "there", "your publication", "general"},
        {"tech@popularmechanics.com", "there", "your publication", "general"},
        {"press@umontreal.ca", "there", "your publication", "general"},
        {"press@amii.ca", "there", "your publication", "general"},
        {"science@house.gov", "there", "your publication", "general"},
        {"tech@wired.co.uk", "there", "your publication", "general"},
        {"press@microsoft.com", "there", "your publication", "general"},
        {"tips@thinkprogress.org", "there", "your publication", "general"},
        {"press@jpmorgan.com", "there", "your publication", "general"},
        {"yoshua@mila.quebec", "there", "your publication", "general"},
        {"press@sxsw.com", "there", "your publication", "general"},
        {"awards@acm.org", "there", "your publication", "general"},
        {"paul@alignment.org", "there", "your publication", "general"},
        {"ai-committee@senate.gov", "there", "your publication", "general"},
        {"press@morganstanley.com", "there", "your publication", "general"},
        {"press@idc.com", "there", "your publication", "general"},
        {"press@safe.ai", "there", "your publication", "general"},
        {"press@discord.com", "there", "your publication", "general"},
        {"tech@winnipegfreepress.com", "there", "your publication", "general"},
        {"tech@usatoday.com", "there", "your publication", "general"},
        {"mark@meta.com", "there", "your publication", "general"},
        {"press@coursera.org", "there", "your publication", "general"},
        {"press@ieee.org", "there", "your publication", "general"},
        {"press@vanguard.com", "there", "your publication", "general"},
        {"press@copilot.com", "there", "your publication", "general"},
        {"press@mozilla.org", "there", "your publication", "general"},
        {"press@mckinsey.com", "there", "your publication", "general"},
        {"press@gartner.com", "there", "your publication", "general"},
        {"press@cboe.com", "there", "your publication", "general"},
        {"press@rogers.com", "there", "your publication", "general"},
        {"tips@medium.com", "there", "your publication", "general"},
        {"press@cmegroup.com", "there", "your publication", "general"},
        {"press@deloitte.com", "there", "your publication", "general"},
        {"press@ualberta.ca", "there", "your publication", "general"},
        {"tech@bostonglobe.com", "there", "your publication", "general"},
        {"press@twitter.com", "there", "your publication", "general"},
        {"press@linkedin.com", "there", "your publication", "general"},
        {"press@meta.com", "there", "your publication", "general"},
        {"press@telus.com", "there", "your publication", "general"},
        {"press@ycombinator.com", "there", "your publication", "general"},
        {"tips@betakit.com", "there", "your publication", "general"},
        {"press@square.com", "there", "your publication", "general"},
        {"press@kaggle.com", "there", "your publication", "general"},
        {"lisa@amd.com", "there", "your publication", "general"},
        {"elon@tesla.com", "there", "your publication", "general"},
        {"tips@techvibes.com", "there", "your publication", "general"},
        {"press@bain.com", "there", "your publication", "general"},
        {"press@freshbooks.com", "there", "your publication", "general"},
        {"press@ritual.com", "there", "your publication", "general"},
        {"press@accenture.com", "there", "your publication", "general"},
        {"tech@latimes.com", "there", "your publication", "general"},
        {"press@americanexpress.com", "there", "your publication", "general"},
        {"press@pwc.com", "there", "your publication", "general"},
        {"tips@substack.com", "there", "your publication", "general"},
        {"press@apple.com", "there", "your publication", "general"},
        {"naval@twitter.com", "there", "your publication", "general"},
        {"press@ey.com", "there", "your publication", "general"},
        {"eliezer@lesswrong.com", "there", "your publication", "general"},
        {"tech@globeandmail.com", "there", "your publication", "general"},
        {"press@hootsuite.com", "there", "your publication", "general"},
        {"press@masterclass.com", "there", "your publication", "general"},
        {"press@jobber.com", "there", "your publication", "general"},
        {"press@mcmaster.ca", "there", "your publication", "general"},
        {"press@gemini.com", "there", "your publication", "general"},
        {"press@descartes.com", "there", "your publication", "general"},
        {"tech@thechronicleherald.ca", "there", "your publication", "general"},
        {"contact@joerogan.com", "there", "your publication", "general"},
        {"press@websummit.com", "there", "your publication", "general"},
        {"shantanu@adobe.com", "there", "your publication", "general"},
        {"press@constellation.com", "there", "your publication", "general"},
        {"press@aws.com", "there", "your publication", "general"},
        {"press@coinbase.com", "there", "your publication", "general"},
        {"press@td.com", "there", "your publication", "general"},
        {"arvind@ibm.com", "there", "your publication", "general"},
        {"tech@chicagotribune.com", "there", "your publication", "general"},
        {"press@sequoiacap.com", "there", "your publication", "general"},
        {"press@cibc.com", "there", "your publication", "general"},
        {"press@datacamp.com", "there", "your publication", "general"},
        {"press@sfu.ca", "there", "your publication", "general"},
        {"press@bmo.com", "there", "your publication", "general"},
        {"press@communitech.ca", "there", "your publication", "general"},
        {"hinton@toronto.edu", "there", "your publication", "general"},
        {"ostp@whitehouse.gov", "there", "your publication", "general"},
        {"press@cato.org", "there", "your publication", "general"},
        {"tech@cbc.ca", "there", "your publication", "general"},
        {"tech@foxnews.com", "there", "your publication", "general"},
        {"mustafa@deepmind.com", "there", "your publication", "general"},
        {"press@caiac.ca", "there", "your publication", "general"},
        {"fei-fei@stanford.edu", "there", "your publication", "general"},
        {"press@lightspeedhq.com", "there", "your publication", "general"},
        {"tech@wired.com", "there", "your publication", "general"},
        {"tech@calgaryherald.com", "there", "your publication", "general"},
        {"kate@ainowinstitute.org", "there", "your publication", "general"},
        {"press@wealthsimple.com", "there", "your publication", "general"},
        {"press@magna.com", "there", "your publication", "general"},
        {"press@nyse.com", "there", "your publication", "general"},
        {"press@uwaterloo.ca", "there", "your publication", "general"},
        {"press@d-id.com", "there", "your publication", "general"},
        {"tech@ctv.ca", "there", "your publication", "general"},
        {"press@mcgill.ca", "there", "your publication", "general"},
        {"press@wellsfargo.com", "there", "your publication", "general"},
        {"press@bnymellon.com", "there", "your publication", "general"},
        {"press@ubc.ca", "there", "your publication", "general"},
        {"press@mila.quebec", "there", "your publication", "general"},
        {"timnit@dair-institute.org", "there", "your publication", "general"},
        {"press@heritage.org", "there", "your publication", "general"},
        {"press@scotiabank.com", "there", "your publication", "general"},
        {"tech@theatlantic.com", "there", "your publication", "general"},
        {"press@patreon.com", "there", "your publication", "general"},
        {"press@bell.ca", "there", "your publication", "general"},
        {"press@wattpad.com", "there", "your publication", "general"},
        {"press@acm.org", "there", "your publication", "general"},
        {"russell@berkeley.edu", "there", "your publication", "general"},
        {"press@ppforum.ca", "there", "your publication", "general"},
        {"press@etrade.com", "there", "your publication", "general"},
        {"contact@lexfridman.com", "there", "your publication", "general"},
        {"press@partnershiponai.org", "there", "your publication", "general"},
        {"press@brookings.edu", "there", "your publication", "general"},
        {"press@techcrunch.com", "there", "your publication", "general"},
        {"press@slack.com", "there", "your publication", "general"},
        {"tech@vancouversun.com", "there", "your publication", "general"},
        {"judea@cs.ucla.edu", "there", "your publication", "general"},
        {"press@robinhood.com", "there", "your publication", "general"},
        {"press@ulaval.ca", "there", "your publication", "general"},
    ""}

    logMsg ("Loaded " & (count of theContacts) & " contacts")
    set totalContacts to count of theContacts
    set batchSize to 50
    set batchNum to 0

    repeat with aContact in theContacts
        if (class of aContact) is string then exit repeat
        set {theEmail, theFirst, theOutlet, theBeat} to aContact
        my createDraft(theEmail, theFirst, theOutlet, theBeat)
        if (totalCreated mod batchSize) = 0 and totalCreated > 0 then
            set batchNum to batchNum + 1
            logMsg ("=== Batch " & batchNum & " complete. Total: " & totalCreated & " / Failed: " & totalFailed & " ===")
            delay 2
        end if
    end repeat

    logMsg ("=== PRESS BLITZ FULL COMPLETE: created=" & totalCreated & " failed=" & totalFailed & " ===")
    display dialog ("Press Blitz complete!" & return & return & "Created: " & totalCreated & return & "Failed: " & totalFailed & return & return & "Next: open Mail.app Drafts, review, then send.") buttons {"OK"} default button "OK"
end run