#!/usr/bin/env python3
"""
canon_mcp_registry.py — Phase 3 Lane 2, Worker 1: Canonical file registry.

Reads all 3 MCP registry files, normalizes to a single canonical schema,
deduplicates by slug, and writes one source of truth.

Sources:
  1. ~/clawd/csoai-org-v2/mcp_registry.json — 14 sites, dict with "sites[]"
  2. ~/clawd/councilof-ai/client/src/data/mcpRegistry.json — 293 servers, dict with "servers[]"
  3. ~/clawd/csoai-org-v2/mcp_packs_registry.json — 5 packs, dict with "packs[]"

Output: ~/clawd/councilof-ai/client/src/data/canonMcpRegistry.ts
"""
import json
import os
from pathlib import Path
from datetime import datetime, timezone

ROOT = Path.home() / "clawd"
SOURCES = [
    ROOT / "csoai-org-v2" / "mcp_registry.json",
    ROOT / "councilof-ai" / "client" / "src" / "data" / "mcpRegistry.json",
    ROOT / "csoai-org-v2" / "mcp_packs_registry.json",
]
OUTPUT = ROOT / "councilof-ai" / "client" / "src" / "data" / "canonMcpRegistry.ts"


def normalize_site(entry: dict) -> dict:
    return {
        "id": entry.get("domain", entry.get("slug", entry.get("name", "unknown"))),
        "name": entry.get("domain", entry.get("name", "unknown")),
        "type": "site",
        "description": entry.get("purpose", entry.get("description", "")),
        "category": entry.get("layer", entry.get("category", "")),
        "url": entry.get("url", ""),
        "geo": entry.get("geo", []),
        "keywords": entry.get("aeo_keywords", []),
        "mcp_enabled": entry.get("mcp_enabled", False),
    }


def normalize_server(entry: dict) -> dict:
    return {
        "id": entry.get("slug", entry.get("name", "unknown")),
        "name": entry.get("name", "unknown"),
        "type": "server",
        "description": entry.get("description", ""),
        "category": entry.get("category", ""),
        "url": entry.get("url", ""),
        "tags": entry.get("tags", []),
        "license": entry.get("license", ""),
    }


def normalize_pack(entry: dict) -> dict:
    return {
        "id": entry.get("id", "unknown"),
        "name": entry.get("name", "unknown"),
        "type": "pack",
        "description": entry.get("description", ""),
        "price_gbp": entry.get("price_gbp", 0),
        "billing_cycle": entry.get("billing_cycle", ""),
        "servers_included": entry.get("servers_included", []),
        "stripe_link": entry.get("stripe_link", ""),
    }


def load_registry(path: Path) -> list[dict]:
    if not path.exists():
        return []
    try:
        data = json.loads(path.read_text())
    except json.JSONDecodeError as e:
        print(f"  ! Failed to parse {path}: {e}")
        return []
    entries: list[dict] = []
    for key in ("sites", "servers", "packs", "mcps", "tools"):
        items = data.get(key) if isinstance(data, dict) else None
        if items is None:
            continue
        if key == "sites":
            entries.extend(normalize_site(e) for e in items)
        elif key == "servers":
            entries.extend(normalize_server(e) for e in items)
        elif key == "packs":
            entries.extend(normalize_pack(e) for e in items)
        elif isinstance(items, list):
            entries.extend(normalize_server(e) for e in items if isinstance(e, dict))
    return entries


def main() -> None:
    print("=== canon_mcp_registry: Phase 3 Lane 2 Worker 1 ===")
    all_entries: list[dict] = []
    seen_ids: set[str] = set()
    for src in SOURCES:
        entries = load_registry(src)
        new_count = 0
        for e in entries:
            if e["id"] not in seen_ids:
                seen_ids.add(e["id"])
                all_entries.append(e)
                new_count += 1
        print(f"  {src.name}: {len(entries)} entries ({new_count} new)")

    counts = {"site": 0, "server": 0, "pack": 0}
    for e in all_entries:
        counts[e["type"]] = counts.get(e["type"], 0) + 1
    print(f"  TOTAL: {len(all_entries)} unique entries")
    for k, v in counts.items():
        print(f"    {k}: {v}")

    ts = datetime.now(timezone.utc).isoformat()
    header = (
        f"// Auto-generated by canon_mcp_registry.py on {ts}\n"
        f"// Source: {len(SOURCES)} registries, {len(all_entries)} unique entries\n"
        f"// Sites: {counts['site']}, Servers: {counts['server']}, Packs: {counts['pack']}\n\n"
    )
    body = (
        "export interface CanonEntry {\n"
        "  id: string;\n"
        "  name: string;\n"
        "  type: 'site' | 'server' | 'pack';\n"
        "  description: string;\n"
        "  category?: string;\n"
        "  url?: string;\n"
        "  geo?: string[];\n"
        "  keywords?: string[];\n"
        "  tags?: string[];\n"
        "  license?: string;\n"
        "  mcp_enabled?: boolean;\n"
        "  price_gbp?: number;\n"
        "  billing_cycle?: string;\n"
        "  servers_included?: string[];\n"
        "  stripe_link?: string;\n"
        "}\n\n"
        f"export const CANON_REGISTRY: CanonEntry[] = {json.dumps(all_entries, indent=2)};\n\n"
        f"export const CANON_COUNTS = {json.dumps(counts)} as const;\n"
    )
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(header + body)
    print(f"  Wrote: {OUTPUT}")


if __name__ == "__main__":
    main()
