#!/usr/bin/env python3
"""make_did.py — regenerate .well-known/did.json from the ACTUAL signing key (single source of truth).

The did:web identity MUST publish the exact key that signs cards, or verification fails. This
derives the public key from the signing keystone and writes did.json. Publishes ONLY the public
key — the private key never leaves the keystone.

Run it wherever the PRODUCTION signing key lives (the A100 keystone). If run on a machine whose
local key differs (e.g. a dev Mac), it publishes that machine's key — which is why the published
identity and the signer can diverge across machines. Reconcile to ONE production key (owner task).

    python3 make_did.py [--key ~/.sovos/city_ed25519] [--domain csoai.org]
"""
from __future__ import annotations

import argparse
import base64
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT / "SOVOS" / "packages" / "sovos-city" / "src"))

_B58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"


def _b58(b: bytes) -> str:
    n = int.from_bytes(b, "big"); s = ""
    while n:
        n, r = divmod(n, 58); s = _B58[r] + s
    return _B58[0] * (len(b) - len(b.lstrip(b"\x00"))) + s


def keystone_pubkey_hex(key_path: str) -> str:
    from cryptography.hazmat.primitives import serialization
    from sovos_city.chain import Chain
    import tempfile
    c = Chain(str(Path(tempfile.gettempdir()) / "_makedid.jsonl"),
              key_path=os.path.expanduser(key_path))
    return c._key.public_key().public_bytes(
        serialization.Encoding.Raw, serialization.PublicFormat.Raw).hex()


def build_did(pub_hex: str, domain: str = "csoai.org") -> dict:
    raw = bytes.fromhex(pub_hex)
    assert len(raw) == 32, "Ed25519 pubkey must be 32 bytes"
    x = base64.urlsafe_b64encode(raw).rstrip(b"=").decode()
    mb = "z" + _b58(b"\xed\x01" + raw)
    did = f"did:web:{domain}"
    return {
        "@context": ["https://www.w3.org/ns/did/v1",
                     "https://w3id.org/security/suites/jws-2020/v1",
                     "https://w3id.org/security/suites/ed25519-2020/v1"],
        "id": did,
        "verificationMethod": [
            {"id": f"{did}#keys-1", "type": "JsonWebKey2020", "controller": did,
             "publicKeyJwk": {"kty": "OKP", "crv": "Ed25519", "x": x,
                              "kid": "csoai-city-ed25519-1", "use": "sig"}},
            {"id": f"{did}#keys-2", "type": "Ed25519VerificationKey2020",
             "controller": did, "publicKeyMultibase": mb},
        ],
        "assertionMethod": [f"{did}#keys-1", f"{did}#keys-2"],
        "authentication": [f"{did}#keys-1"],
        "service": [{"id": f"{did}#verifier", "type": "AttestationVerifier",
                     "serviceEndpoint": f"https://{domain}/verify"}],
        "_note": ("CSOAI signing identity. Ed25519 today (ML-DSA-65 is roadmap, not present). "
                  "Generated by make_did.py from the signing keystone — regenerate on the "
                  "production keystone so the published key equals the one that signs. "
                  "C2PA-trust-list / CA recognition is a separate owner-gated step, not claimed here."),
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--key", default="~/.sovos/city_ed25519")
    ap.add_argument("--domain", default="csoai.org")
    a = ap.parse_args()
    pub = keystone_pubkey_hex(a.key)
    did = build_did(pub, a.domain)
    out = ROOT / ".well-known" / "did.json"
    out.parent.mkdir(exist_ok=True)
    out.write_text(json.dumps(did, indent=2) + "\n")
    print(f"  wrote {out} for pubkey {pub}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
