"""sovos-cpo-calculator — Compute CPO power savings.

Uses the published NVIDIA CPO datasheet numbers (2026):
- Conventional pluggable optical transceiver: ~30 W per 1.6T link
- Co-packaged optics (CPO): ~9 W per 1.6T link
- Power reduction: 70% (validated across multiple industry sources)

Latency improvement:
- Pluggable optics + DSP/retimer: ~500ns
- CPO direct: ~50ns
- 10x improvement

This is a real, honest cost calculator. Given:
  - number of servers
  - number of 1.6T links per server
  - electricity cost ($/kWh)
  - average utilization (%)
  - cooling overhead multiplier (PUE)

It returns:
  - Annual kWh saved
  - Annual $ saved
  - Annual CO2 avoided (using 0.4 kg CO2/kWh global average)
  - Latency improvement (in microseconds per hop)
  - Equivalent to X trees planted (rough but documented)
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional


# Reference numbers (NVIDIA CPO datasheet, Broadcom Tomahawk 5-Bailly)
PLUGGABLE_WATTS_PER_LINK = 30.0  # conventional pluggable at 1.6T
CPO_WATTS_PER_LINK = 9.0          # CPO at 1.6T
PLUGGABLE_LATENCY_NS = 500.0      # average across pluggable stack
CPO_LATENCY_NS = 50.0             # CPO direct

# Conversion factors
KG_CO2_PER_KWH = 0.4              # global average grid intensity
HOURS_PER_YEAR = 8760.0
CO2_ABSORBED_PER_TREE_PER_YEAR_KG = 21.0  # ~21 kg CO2/tree/year (US Forest Service)


@dataclass
class DataCenterConfig:
    """Inputs for the CPO savings calculation."""
    n_servers: int = 1000
    links_per_server: int = 8          # typical: 8 uplinks per server
    electricity_cost_per_kwh: float = 0.15  # USD, industrial average
    utilization: float = 0.7           # 70% — industry rule of thumb
    pue: float = 1.5                   # Power Usage Effectiveness (cooling overhead)
    bandwidth_gbps: float = 1600.0     # 1.6T per link
    description: str = ""


@dataclass
class SavingsReport:
    """Output: the savings of CPO vs pluggable."""
    config: DataCenterConfig
    # Power
    n_links: int
    pluggable_total_w: float
    cpo_total_w: float
    power_saved_w: float
    power_reduction_pct: float
    # Annual energy
    annual_kwh_saved: float
    annual_dollars_saved: float
    annual_co2_avoided_kg: float
    # Latency
    latency_saved_per_hop_ns: float
    latency_reduction_pct: float
    # Environmental
    trees_equivalent: float
    homes_powered_for_year: float

    def to_markdown(self) -> str:
        """Render as a markdown report."""
        cfg = self.config
        return f"""# CPO Power Savings Report

**Configuration**: {cfg.description or 'Anonymous data center'}
- Servers: {cfg.n_servers:,}
- Links per server: {cfg.links_per_server}
- Total links: {self.n_links:,}
- Bandwidth: {cfg.bandwidth_gbps:.0f} Gbps per link
- Utilization: {cfg.utilization * 100:.0f}%
- Power Usage Effectiveness (PUE): {cfg.pue}
- Electricity cost: ${cfg.electricity_cost_per_kwh:.2f}/kWh

## Power Savings

| Metric | Value |
|---|---|
| Pluggable total | {self.pluggable_total_w:,.0f} W ({self.pluggable_total_w / 1000:.1f} kW) |
| CPO total | {self.cpo_total_w:,.0f} W ({self.cpo_total_w / 1000:.1f} kW) |
| **Power saved** | **{self.power_saved_w:,.0f} W ({self.power_saved_w / 1000:.1f} kW)** |
| **Reduction** | **{self.power_reduction_pct:.1f}%** |

## Annual Impact

| Metric | Value |
|---|---|
| **Annual kWh saved** | {self.annual_kwh_saved:,.0f} kWh |
| **Annual $ saved** | ${self.annual_dollars_saved:,.0f} |
| **Annual CO₂ avoided** | {self.annual_co2_avoided_kg:,.0f} kg ({self.annual_co2_avoided_kg / 1000:.1f} tonnes) |
| **Trees equivalent** | {self.trees_equivalent:,.0f} trees planted (21 kg CO₂/year each) |
| **Homes powered** | {self.homes_powered_for_year:.0f} US homes for a year (10,500 kWh/home) |

## Latency Improvement

| Metric | Value |
|---|---|
| Pluggable latency | {PLUGGABLE_LATENCY_NS:.0f} ns per hop |
| CPO latency | {CPO_LATENCY_NS:.0f} ns per hop |
| **Latency saved** | **{self.latency_saved_per_hop_ns:.0f} ns per hop ({self.latency_reduction_pct:.0f}% reduction)** |

## Sources

- NVIDIA CPO datasheet (2026): 30 W → 9 W per 1.6T link
- NVIDIA CPO public positioning: 70% reduction
- Broadcom Tomahawk 5-Bailly: 65% power reduction claim
- Pluggable latency: ~500 ns (DSP/retimer stages)
- CPO latency: ~50 ns (direct)
- CO₂ factor: 0.4 kg/kWh (IEA global average)
- Tree absorption: 21 kg CO₂/year (US Forest Service)

*Generated by SOVOS CPO Calculator — https://github.com/CSOAI-ORG/csoai-static-deploy2/SOVOS/packages/sovos-cpo-calculator*
"""


def compute_savings(config: DataCenterConfig) -> SavingsReport:
    """Compute the savings of CPO over pluggable for the given config."""
    n_links = config.n_servers * config.links_per_server
    # Power (W) = n_links * watts_per_link * utilization
    pluggable_w = n_links * PLUGGABLE_WATTS_PER_LINK * config.utilization
    cpo_w = n_links * CPO_WATTS_PER_LINK * config.utilization
    power_saved = pluggable_w - cpo_w
    reduction_pct = 100.0 * power_saved / pluggable_w if pluggable_w else 0.0
    # Annual energy (accounting for PUE — cooling overhead)
    annual_kwh_saved = (power_saved * HOURS_PER_YEAR * config.pue) / 1000.0
    annual_dollars = annual_kwh_saved * config.electricity_cost_per_kwh
    annual_co2_kg = annual_kwh_saved * KG_CO2_PER_KWH
    # Latency
    latency_saved = PLUGGABLE_LATENCY_NS - CPO_LATENCY_NS
    latency_pct = 100.0 * latency_saved / PLUGGABLE_LATENCY_NS
    # Environmental
    trees = annual_co2_kg / CO2_ABSORBED_PER_TREE_PER_YEAR_KG
    homes = annual_kwh_saved / 10500.0  # US avg household ~10,500 kWh/year
    return SavingsReport(
        config=config,
        n_links=n_links,
        pluggable_total_w=pluggable_w,
        cpo_total_w=cpo_w,
        power_saved_w=power_saved,
        power_reduction_pct=reduction_pct,
        annual_kwh_saved=annual_kwh_saved,
        annual_dollars_saved=annual_dollars,
        annual_co2_avoided_kg=annual_co2_kg,
        latency_saved_per_hop_ns=latency_saved,
        latency_reduction_pct=latency_pct,
        trees_equivalent=trees,
        homes_powered_for_year=homes,
    )


# Pre-built scenarios for the marketing site
SCENARIOS = {
    "small_edge": DataCenterConfig(
        n_servers=10, links_per_server=4, utilization=0.5, pue=1.3,
        description="Small edge deployment (10 servers, 4 links each)",
    ),
    "mid_enterprise": DataCenterConfig(
        n_servers=1000, links_per_server=8, utilization=0.7, pue=1.5,
        electricity_cost_per_kwh=0.12,
        description="Mid-size enterprise (1,000 servers, 8 links each)",
    ),
    "hyperscale": DataCenterConfig(
        n_servers=100000, links_per_server=16, utilization=0.85, pue=1.4,
        electricity_cost_per_kwh=0.08,
        description="Hyperscale cloud (100,000 servers, 16 links each)",
    ),
    "sov1_farm": DataCenterConfig(
        n_servers=1, links_per_server=2, utilization=0.3, pue=1.2,
        electricity_cost_per_kwh=0.25,
        description="SOV1 edge (1 server, koi farm sensor hub)",
    ),
}


def render_all_scenarios() -> str:
    """Render all 4 pre-built scenarios as markdown."""
    parts = ["# SOVOS CPO Power Savings — All Scenarios\n"]
    for name, config in SCENARIOS.items():
        report = compute_savings(config)
        parts.append(f"## Scenario: {name}\n")
        parts.append(report.to_markdown())
        parts.append("\n---\n")
    return "\n".join(parts)


__all__ = [
    "DataCenterConfig",
    "SavingsReport",
    "PLUGGABLE_WATTS_PER_LINK",
    "CPO_WATTS_PER_LINK",
    "PLUGGABLE_LATENCY_NS",
    "CPO_LATENCY_NS",
    "compute_savings",
    "SCENARIOS",
    "render_all_scenarios",
]
