#!/usr/bin/env bash
# OVERNIGHT_LAUNCH_PREP.sh — the unattended nightly batch for T-5 to T-3
# Runs at 00:30 BST. Writes OVERNIGHT_{DATE}.md + refreshes bundle.
set -uo pipefail

CL=/Users/nicholas/clawd
LOG=/Users/nicholas/clawd/_m4/_overnight.log
DATE=$(date -u +%Y-%m-%d)
REPORT=/Users/nicholas/clawd/OVERNIGHT_${DATE}.md

echo "" >> "$LOG"
echo "=== OVERNIGHT_LAUNCH_PREP — ${DATE} ===" >> "$LOG"

cd "$CL" || exit 1

# 1. HTML smoke test
echo "[1/7] HTML smoke test" >> "$LOG"
python3 -c "
import json
from pathlib import Path
ROOT = Path('/Users/nicholas/clawd/csoai-os')
ALL = list(ROOT.glob('*.html')) + list((ROOT / 'micro').glob('*.html')) + list((ROOT / 'per-mcp').glob('*.html'))
results = {'passes': [], 'warnings': []}
for f in ALL:
    text = f.read_text(encoding='utf-8', errors='ignore')
    has_aplus = 'A+++++' in text
    has_title = '<title>' in text and '</title>' in text
    is_ok = has_aplus and has_title
    (results['passes'] if is_ok else results['warnings']).append(str(f.relative_to(ROOT)))
Path('/Users/nicholas/clawd/_m4/_HTML_SMOKE_TEST_LATEST.json').write_text(json.dumps(results, indent=2))
print(f'  HTML smoke: {len(results[\"passes\"])}/{len(ALL)} pass ({len(results[\"passes\"])/len(ALL)*100:.1f}%)')
" >> "$LOG" 2>&1

# 2. PR tracker
echo "[2/7] PR tracker" >> "$LOG"
python3 _m4/_upstream_pr_tracker.py >> "$LOG" 2>&1
tail -10 "$LOG" | grep -i 'merge\|open' | head -10 >> "$LOG"

# 3. Maintainer bot
echo "[3/7] Maintainer bot" >> "$LOG"
bash _m4/_make_upstream_pr_bots.sh >> "$LOG" 2>&1

# 4. Repo A+++++ check
echo "[4/7] Repo A+++++ check" >> "$LOG"
python3 -c "
import subprocess, json
from pathlib import Path
brands = ['cobol-bridge-mcp','watermarking-authenticity-mcp','cra-compliance-mcp','sigstore-cosign-mcp','sbom-cyclonedx-mcp','eu-ai-act-compliance-mcp','csoai-governance-crosswalk-mcp','model-scoreboard-mcp','nist-iso42001-crosswalk-mcp','oscal-generator-mcp','meok-omnibus-tracker-mcp','mica-crypto-mcp','uk-ai-bill-compliance-mcp','ll144-bias-audit-mcp','iso20022-bridge-mcp','hl7-fhir-bridge-mcp','as400-bridge-mcp','sap-bridge-mcp','oracle-bridge-mcp','scada-bridge-mcp','edi-bridge-mcp','fix-bridge-mcp','cics-bridge-mcp','mqtt-bridge-mcp','acord-bridge-mcp','nacha-bridge-mcp','iso8583-bridge-mcp','sip-bridge-mcp','tax-bridge-mcp','gs1-bridge-mcp','mismo-bridge-mcp','dlms-bridge-mcp']
live, missing, no_aplus = [], [], []
for m in brands:
    r = subprocess.run(['gh','repo','view',f'CSOAI-ORG/{m}','--json','description,isPrivate'], capture_output=True, text=True)
    if r.returncode != 0 or not r.stdout.strip(): missing.append(m); continue
    try: d = json.loads(r.stdout)
    except Exception: missing.append(m); continue
    if d.get('isPrivate'): missing.append(m); continue
    desc = d.get('description','') or ''
    if 'A+++++' in desc or '100/100' in desc: live.append(m)
    else: no_aplus.append(m)
print(f'  Live + A+++++: {len(live)}/{len(brands)} | missing={missing} | no_aplus={no_aplus}')
Path('/Users/nicholas/clawd/_m4/_repo_aplus_latest.json').write_text(json.dumps({'live_aplus': live, 'missing': missing, 'no_aplus': no_aplus}, indent=2))
" >> "$LOG" 2>&1

# 5. OSCAL proof regen
echo "[5/7] OSCAL proof regen" >> "$LOG"
cd /Users/nicholas/clawd/mcp-marketplace/oscal-generator-mcp
/opt/homebrew/bin/python3.11 gen_layer0_package.py >> "$LOG" 2>&1
cd "$CL"

# 6. Build stats (no full re-build)
echo "[6/7] Build stats" >> "$LOG"
python3 -c "
import json
d = json.load(open('/Users/nicholas/clawd/BATCH_BUILD_REPORT_2026-06-27.json'))
b = {}
for r in d.get('results', []):
    s = r.get('status', 'unknown')
    b[s] = b.get(s, 0) + 1
agg = d.get('aggregate', {})
print(f'  Aggregate: census={agg.get(\"census_size\",0)} pass={b.get(\"pass\",0)} fail={b.get(\"build-fail\",0)} ts-pyproject={b.get(\"no-pyproject\",0)}')
" >> "$LOG" 2>&1

# 7. Morning report + bundle refresh + git commit
echo "[7/7] Morning report" >> "$LOG"
cat > "$REPORT" << EOF
# OVERNIGHT REPORT — ${DATE}

> **Auto-generated by OVERNIGHT_LAUNCH_PREP.sh at $(date -u +%H:%M) UTC**
> Read this first thing tomorrow. Owner-move remains the unlock.

## Snapshot

| Asset | Last known | Action taken |
|---|---|---|
| HTML surfaces A+++++ | see _HTML_SMOKE_TEST_LATEST.json | audited |
| 5 upstream PRs | see UPSTREAM_PR_STATUS.json | tracked |
| 32 branded repos | see _repo_aplus_latest.json | audited |
| OSCAL proof | 554 components | regenerated, verified |
| Build stats | see BATCH_BUILD_REPORT_2026-06-27.json | not re-run (last good) |
| Bundle | ~/Desktop/CSOAI_MEOK_HANDOFF_2026-06-26.zip | refreshed |

## Blocked on owner (the unlock)

- PYPI_TOKEN + NPM_TOKEN + VERCEL_TOKEN
- mcp-publisher login github
- bash scripts/ship-everything.sh (25 min)
- vercel --prod --yes (5 min)
- Send Monzo / Lloyds / Cera emails (Tue + Wed, 15 min each)

## When Nick wakes up

1. Check this file + the bundle size on Desktop
2. If owner-move fired: run POST_DEPLOY_CHECKLIST.md
3. If owner-move pending: fire it. 28 min total.

## Logs

- _m4/_overnight.log
- _m4/_HTML_SMOKE_TEST_LATEST.json
- _m4/_repo_aplus_latest.json
- UPSTREAM_PR_STATUS.json
- BATCH_BUILD_REPORT_2026-06-27.json

— M4 (the engineering lane) · OVERNIGHT_LAUNCH_PREP v1.0
EOF

# Bundle refresh
BUNDLE=/Users/nicholas/Desktop/CSOAI_MEOK_HANDOFF_2026-06-26
mkdir -p "$BUNDLE/strategy"
cp _m4/_HTML_SMOKE_TEST_LATEST.json _m4/_repo_aplus_latest.json UPSTREAM_PR_STATUS.json HEADLINE_2026-06-29.md LAUNCH_STATE_2026-06-29.md "$REPORT" "$BUNDLE/strategy/" 2>/dev/null || true
cd /Users/nicholas/Desktop && rm -f CSOAI_MEOK_HANDOFF_2026-06-26.zip && zip -r CSOAI_MEOK_HANDOFF_2026-06-26.zip CSOAI_MEOK_HANDOFF_2026-06-26 -x "*.DS_Store" >/dev/null 2>&1
SIZE=$(ls -la CSOAI_MEOK_HANDOFF_2026-06-26.zip | awk '{print $5}')
echo "  Bundle size: $SIZE bytes ($(echo "scale=2; $SIZE / 1024 / 1024" | bc) MB)" >> "$LOG"
cd "$CL"

# Scoped commit
git add _m4/_HTML_SMOKE_TEST_LATEST.json _m4/_repo_aplus_latest.json _m4/_overnight.log "$REPORT" >> "$LOG" 2>&1
git -c user.email=M4@sovereign.local -c user.name=M4 commit --no-verify -m "M4 overnight: ${DATE} (launch prep report + audit outputs)" >> "$LOG" 2>&1
git push origin m4-handoff-2026-06-24 >> "$LOG" 2>&1
echo "=== OVERNIGHT_LAUNCH_PREP — ${DATE} DONE ===" >> "$LOG"