"""mcp-governance-crosswalk — reference MCP server (sourced from PyPI).

This is the deployment reference. The actual server source lives at:
    https://pypi.org/project/csoai-governance-crosswalk-mcp/

This package's role in the monorepo is to:
    1. Document the deployment pattern (Dockerfile, sovos.yaml, tests)
    2. Show how a PyPI-published MCP plugs into the SOVOS stack
    3. Provide a working test harness for the deployment contract

Do NOT edit this file thinking it will change the PyPI package. The PyPI
package is canonical; this is a deployment mirror.
"""
from __future__ import annotations

import json
import logging
import os
from typing import Any, Dict, List

logger = logging.getLogger(__name__)

# Cross-walk between frameworks — the actual data lives in the PyPI package,
# we ship a stub here so the monorepo test suite can run.
FRAMEWORKS = (
    "EU_AI_ACT", "NIST_RMF", "ISO_42001", "DORA", "GDPR", "NIS2",
)

# Sample cross-walk: EU AI Act Article 5 ↔ NIST RMF GOVERN ↔ ISO 42001 Clause 5
SAMPLE_CROSSWALK = [
    {
        "source": "EU AI Act Article 5 (Prohibited Practices)",
        "nist_rmf": "GOVERN-1.1 (Legal/Regulatory Requirements)",
        "iso_42001": "Clause 5.2 (Policy)",
        "dora": "Article 18 (ICT Risk Management)",
    },
    {
        "source": "EU AI Act Article 9 (Risk Management)",
        "nist_rmf": "MANAGE-2.2 (Risk Management Plan)",
        "iso_42001": "Clause 6.1.2 (AI Risk Identification)",
        "dora": "Article 18 (ICT Risk Management)",
    },
    {
        "source": "EU AI Act Article 10 (Data Governance)",
        "nist_rmf": "MAP-2.1 (Data Quality)",
        "iso_42001": "Clause 8.5 (Data for AI Systems)",
        "gdpr": "Article 5 (Principles relating to processing)",
    },
]


def crosswalk(query: str) -> List[Dict[str, str]]:
    """Return the cross-walk entries matching the query string.

    Real implementation lives in the PyPI package; this stub returns
    SAMPLE_CROSSWALK for any non-empty query.
    """
    if not query or not query.strip():
        return []
    return SAMPLE_CROSSWALK


def frameworks_loaded() -> List[str]:
    """Return the list of frameworks this server supports."""
    return list(FRAMEWORKS)


# MCP tool handlers (the real ones come from PyPI; this is a stub)
def handle_tool_call(name: str, args: Dict[str, Any]) -> Dict[str, Any]:
    if name == "crosswalk":
        return {"results": crosswalk(args.get("query", ""))}
    if name == "frameworks":
        return {"frameworks": frameworks_loaded()}
    return {"error": f"unknown tool: {name}"}


__all__ = ["crosswalk", "frameworks_loaded", "handle_tool_call", "FRAMEWORKS", "SAMPLE_CROSSWALK"]