// CSOAI App.tsx — EAT-LAZY: route-level code-splitting
// Generated by: JEEVES (Hermes sovereign teammate)
// Strategy:
//   - Eager (kept): framework, providers, Header/Footer, AND THE HOMEPAGE (NewHomeV2)
//     because that's the first-paint critical path.
//   - Lazy: every other page is dynamic-imported with React.lazy + Suspense.
//   - All wouter <Route path=... component={X}> entries preserved so navigation
//     semantics are unchanged. We only swapped the component source.
//
// Expected impact: app chunk drops from ~4.3 MB to ~1-1.5 MB on first paint.
// Each route's code is fetched on demand and cached by Vite.

import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Route, Switch, useLocation } from "wouter";
import { useEffect } from "react";
import ErrorBoundary from "./components/ErrorBoundary";
import { ThemeProvider } from "./contexts/ThemeContext";
import { AuthProvider } from "./contexts/AuthContext";
import { Header } from "./components/Header";
import { Footer } from "./components/Footer";
import { SkipNavigation } from "./components/SkipNavigation";
import { lazyRoute, RouteSkeleton } from "./lib/lazyRoute";

// Eager: home page only (critical first-paint)
import NewHomeV2 from "./pages/NewHome-v2";

// Lazy: every other page
const NotFound = lazyRoute(() => import("./pages/NotFound"));
const Landing = lazyRoute(() => import("./pages/Landing"));
const Dashboard = lazyRoute(() => import("./pages/Dashboard"));
const AISystems = lazyRoute(() => import("./pages/AISystems"));
const RiskAssessment = lazyRoute(() => import("./pages/RiskAssessment"));
const Compliance = lazyRoute(() => import("./pages/Compliance"));
const AgentCouncil = lazyRoute(() => import("./pages/AgentCouncil"));
const Protocol0 = lazyRoute(() => import("./pages/Protocol0"));
const Watchdog = lazyRoute(() => import("./pages/Watchdog"));
const Reports = lazyRoute(() => import("./pages/Reports"));
const Settings = lazyRoute(() => import("./pages/Settings"));
const WatchdogSignup = lazyRoute(() => import("./pages/WatchdogSignup"));
const TrainingV2 = lazyRoute(() => import("./pages/Training-v2"));
const Courses = lazyRoute(() => import("./pages/Courses"));
const MyCourses = lazyRoute(() => import("./pages/MyCourses"));
const CoursePlayer = lazyRoute(() => import("./pages/CoursePlayer"));
const Certification = lazyRoute(() => import("./pages/Certification"));
const CertificationV2 = lazyRoute(() => import("./pages/Certification-v2"));
const CertificationExam = lazyRoute(() => import("./pages/CertificationExam"));
const CertificationResults = lazyRoute(() => import("./pages/CertificationResults"));
const MyCertificates = lazyRoute(() => import("./pages/MyCertificates"));
const ExamReview = lazyRoute(() => import("./pages/ExamReview"));
const Workbench = lazyRoute(() => import("./pages/Workbench"));
const PublicHome = lazyRoute(() => import("./pages/PublicHome"));
const Admin = lazyRoute(() => import("./pages/Admin"));
const ApiDocs = lazyRoute(() => import("./pages/ApiDocs"));
const ApiKeys = lazyRoute(() => import("./pages/ApiKeys"));
const PDCACycles = lazyRoute(() => import("./pages/PDCACycles"));
const Billing = lazyRoute(() => import("./pages/Billing"));
const PublicDashboard = lazyRoute(() => import("./pages/PublicDashboard"));
const ComplianceScorecard = lazyRoute(() => import("./pages/ComplianceScorecard"));
const KnowledgeBase = lazyRoute(() => import("./pages/KnowledgeBase"));
const EnterpriseOnboarding = lazyRoute(() => import("./pages/EnterpriseOnboarding"));
const Pricing = lazyRoute(() => import("./pages/Pricing"));
const WatchdogLeaderboard = lazyRoute(() => import("./pages/WatchdogLeaderboard"));
const RegulatorDashboard = lazyRoute(() => import("./pages/RegulatorDashboard"));
const Blog = lazyRoute(() => import("./pages/Blog"));
const Recommendations = lazyRoute(() => import("./pages/Recommendations"));
const MarketingHome = lazyRoute(() => import("./pages/MarketingHome"));
const Standards = lazyRoute(() => import("./pages/Standards"));
const Resources = lazyRoute(() => import("./pages/Resources"));
const About = lazyRoute(() => import("./pages/About"));
const Careers = lazyRoute(() => import("./pages/Careers"));
const Login = lazyRoute(() => import("./pages/Login"));
const Signup = lazyRoute(() => import("./pages/Signup"));
const ComplianceMonitoring = lazyRoute(() => import("./pages/ComplianceMonitoring"));
const BulkAISystemImport = lazyRoute(() => import("./pages/BulkAISystemImport"));
const Jobs = lazyRoute(() => import("./pages/Jobs"));
const NotificationSettings = lazyRoute(() => import("./pages/NotificationSettings"));
const MyApplications = lazyRoute(() => import("./pages/MyApplications"));
const VerifyCertificate = lazyRoute(() => import("./pages/VerifyCertificate"));
const AgentCouncilFeature = lazyRoute(() => import("./pages/features/AgentCouncilFeature"));
const PDCAFrameworkFeature = lazyRoute(() => import("./pages/features/PDCAFrameworkFeature"));
const TrainingCertificationFeature = lazyRoute(() => import("./pages/features/TrainingCertificationFeature"));
const WatchdogJobsFeature = lazyRoute(() => import("./pages/features/WatchdogJobsFeature"));
const StudentProgress = lazyRoute(() => import("./pages/StudentProgress"));
const Accreditation = lazyRoute(() => import("./pages/Accreditation"));
const SOAIPDCAFramework = lazyRoute(() => import("./pages/SOAIPDCAFramework"));
const PDCASimulator = lazyRoute(() => import("./pages/PDCASimulator"));
const CertificateVerification = lazyRoute(() => import("./pages/CertificateVerification"));
const EnterpriseDashboard = lazyRoute(() => import("./pages/EnterpriseDashboard"));
const Enterprise = lazyRoute(() => import("./pages/Enterprise"));
const ProsperityFund = lazyRoute(() => import("./pages/ProsperityFund"));
const Charter = lazyRoute(() => import("./pages/Charter"));
const FoundingMembers = lazyRoute(() => import("./pages/FoundingMembers"));
const PublicWatchdog = lazyRoute(() => import("./pages/PublicWatchdog"));
const GovernmentDashboard = lazyRoute(() => import("./pages/GovernmentDashboard"));
const MaternalCovenant = lazyRoute(() => import("./pages/MaternalCovenant"));
const EUAIActGuide = lazyRoute(() => import("./pages/EUAIActGuide"));
const NISTAIRMFGuide = lazyRoute(() => import("./pages/NISTAIRMFGuide"));
const ISO42001Guide = lazyRoute(() => import("./pages/ISO42001Guide"));
const TC260Guide = lazyRoute(() => import("./pages/TC260Guide"));
const WhyCSOAI = lazyRoute(() => import("./pages/WhyCSOAI"));
const Article50Kit = lazyRoute(() => import("./pages/Article50Kit"));
const ComplianceMap = lazyRoute(() => import("./pages/ComplianceMap"));
const MembershipAgreement = lazyRoute(() => import("./pages/legal/MembershipAgreement"));
const FoundingCouncilAgreement = lazyRoute(() => import("./pages/legal/FoundingCouncilAgreement"));
const LicensingAgreement = lazyRoute(() => import("./pages/legal/LicensingAgreement"));
const PrivacyPolicy = lazyRoute(() => import("./pages/legal/PrivacyPolicy"));
const TermsOfService = lazyRoute(() => import("./pages/legal/TermsOfService"));
const Disclaimers = lazyRoute(() => import("./pages/legal/Disclaimers"));
const DataProcessingAgreement = lazyRoute(() => import("./pages/legal/DataProcessingAgreement"));
const CookiePolicy = lazyRoute(() => import("./pages/legal/CookiePolicy"));
const ServiceLevelAgreement = lazyRoute(() => import("./pages/legal/ServiceLevelAgreement"));
const Council = lazyRoute(() => import("./pages/Council"));
const CouncilDome = lazyRoute(() => import("./pages/CouncilDome"));
const CouncilDomains = lazyRoute(() => import("./pages/CouncilDomains"));
const CouncilMaps = lazyRoute(() => import("./pages/CouncilMaps"));
const CouncilCompliance = lazyRoute(() => import("./pages/CouncilCompliance"));
const CouncilLaw = lazyRoute(() => import("./pages/CouncilLaw"));
const CouncilSigil = lazyRoute(() => import("./pages/CouncilSigil"));

import { ScrollToTop } from "./components/ScrollToTop";
import { AnalyticsProvider } from "./contexts/AnalyticsContext";
function RouteAnnouncer() {
  const [location] = useLocation();

  useEffect(() => {
    // Get the page title or create one from the path
    const getPageTitle = () => {
      const title = document.title;
      if (title) return title;

      // Fallback: create title from path
      const path = location.replace(/^\//, '').replace(/-/g, ' ');
      return path ? path.charAt(0).toUpperCase() + path.slice(1) : 'Home';
    };

    // Announce the new page to screen readers
    const announcement = document.createElement('div');
    announcement.setAttribute('role', 'status');
    announcement.setAttribute('aria-live', 'polite');
    announcement.setAttribute('aria-atomic', 'true');
    announcement.className = 'sr-only';
    announcement.style.cssText = `
      position: absolute;
      width: 1px;
      height: 1px;
      padding: 0;
      margin: -1px;
      overflow: hidden;
      clip: rect(0, 0, 0, 0);
      white-space: nowrap;
      border: 0;
    `;

    document.body.appendChild(announcement);

    // Delay announcement slightly to ensure it's picked up
    const timeoutId = setTimeout(() => {
      announcement.textContent = `Navigated to ${getPageTitle()}`;
    }, 100);

    // Clean up
    const cleanupId = setTimeout(() => {
      document.body.removeChild(announcement);
    }, 1000);

    return () => {
      clearTimeout(timeoutId);
      clearTimeout(cleanupId);
      if (announcement.parentNode) {
        document.body.removeChild(announcement);
      }
    };
  }, [location]);

  return null;
}

function App() {
  return (
    <ErrorBoundary>
      <ThemeProvider defaultTheme="light">
        <AuthProvider>
          <AnalyticsProvider>
            <TooltipProvider>
              <div className="flex flex-col min-h-screen">
                {/* Skip Navigation - must be first focusable element */}
                <SkipNavigation />
                <ScrollToTop />
                <RouteAnnouncer />
                <Header />
                <main
                  id="main-content"
                  className="flex-1"
                  role="main"
                  aria-label="Main content"
                  tabIndex={-1}
                >
                  <Suspense fallback={<RouteSkeleton />}>
                  <Switch>
                  {/* Main routes */}
                  <Route path="/" component={NewHomeV2} />
                  <Route path="/login" component={Login} />
                  <Route path="/signup" component={Signup} />
                  <Route path="/marketing" component={MarketingHome} />
                  <Route path="/standards" component={Standards} />
                  <Route path="/resources" component={Resources} />
                  <Route path="/about" component={About} />
                  <Route path="/careers" component={Careers} />
                  {/* Key CSOAI pages */}
                  <Route path="/charter" component={Charter} />
                  <Route path="/maternal-covenant" component={MaternalCovenant} />
                  <Route path="/covenant" component={MaternalCovenant} />
                  <Route path="/why-csoai" component={WhyCSOAI} />
                  <Route path="/our-difference" component={WhyCSOAI} />
                  <Route path="/why" component={WhyCSOAI} />
                  <Route path="/article-50-kit" component={Article50Kit} />
                  <Route path="/eu-ai-act/article-50" component={Article50Kit} />
                  <Route path="/kit" component={Article50Kit} />
                  <Route path="/compliance-map" component={ComplianceMap} />
                  <Route path="/map/regulations" component={ComplianceMap} />
                  <Route path="/map/regimes" component={ComplianceMap} />
                  {/* AI Framework Guides */}
                  <Route path="/eu-ai-act" component={EUAIActGuide} />
                  <Route path="/frameworks/eu-ai-act" component={EUAIActGuide} />
                  <Route path="/nist-ai-rmf" component={NISTAIRMFGuide} />
                  <Route path="/frameworks/nist" component={NISTAIRMFGuide} />
                  <Route path="/iso-42001" component={ISO42001Guide} />
                  <Route path="/frameworks/iso-42001" component={ISO42001Guide} />
                  <Route path="/tc260" component={TC260Guide} />
                  <Route path="/frameworks/tc260" component={TC260Guide} />
                  {/* Additional /guides/ routes for internal navigation */}
                  <Route path="/guides/eu-ai-act" component={EUAIActGuide} />
                  <Route path="/guides/nist-ai-rmf" component={NISTAIRMFGuide} />
                  <Route path="/guides/iso-42001" component={ISO42001Guide} />
                  <Route path="/guides/tc260" component={TC260Guide} />
                  <Route path="/prosperity" component={ProsperityFund} />
                  <Route path="/prosperity-fund" component={ProsperityFund} />
                  <Route path="/founding-members" component={FoundingMembers} />
                  <Route path="/byzantine" component={AgentCouncil} />
                  <Route path="/council" component={CouncilDome} />
                  <Route path="/council/overview" component={Council} />
                  <Route path="/council/dome" component={CouncilDomains} />
                  <Route path="/council/maps" component={CouncilMaps} />
                  <Route path="/council/compliance" component={CouncilCompliance} />
                  <Route path="/council/law" component={CouncilLaw} />
                  <Route path="/council/sigil" component={CouncilSigil} />
                  <Route path="/public-watchdog" component={PublicWatchdog} />
                  <Route path="/government" component={GovernmentDashboard} />
                  <Route path="/government-dashboard" component={GovernmentDashboard} />
                  {/* old-home route removed - was using broken Home component */}
                  <Route path="/landing" component={Landing} />
                  <Route path="/dashboard" component={Dashboard} />
                  <Route path="/ai-systems" component={AISystems} />
                  <Route path="/risk-assessment" component={RiskAssessment} />
                  <Route path="/compliance" component={Compliance} />
                  <Route path="/agent-council" component={AgentCouncil} />
                  <Route path="/protocol0" component={Protocol0} />
                  <Route path="/watchdog" component={Watchdog} />
                  <Route path="/reports" component={Reports} />
                  <Route path="/settings" component={Settings} />
                  <Route path="/settings/billing" component={Billing} />
                  <Route path="/settings/notifications" component={NotificationSettings} />
                  <Route path="/watchdog-signup" component={WatchdogSignup} />
                  <Route path="/training" component={TrainingV2} />
                  <Route path="/courses" component={Courses} />
                  <Route path="/my-courses" component={MyCourses} />
                  <Route path="/dashboard/progress" component={StudentProgress} />
                  <Route path="/courses/:id/learn" component={CoursePlayer} />
                  <Route path="/verify-certificate/:id" component={VerifyCertificate} />
                  <Route path="/features/33-agent-council" component={AgentCouncilFeature} />
                  <Route path="/features/pdca-framework" component={PDCAFrameworkFeature} />
                  <Route path="/features/training-certification" component={TrainingCertificationFeature} />
                  <Route path="/features/watchdog-jobs" component={WatchdogJobsFeature} />
                  <Route path="/certification" component={CertificationV2} />
                  <Route path="/certification/exam" component={CertificationExam} />
                  <Route path="/certification/results" component={CertificationResults} />
                  <Route path="/certificates" component={MyCertificates} />
                  <Route path="/certification/review" component={ExamReview} />
                  <Route path="/workbench" component={Workbench} />
                  <Route path="/jobs" component={Jobs} />
                  <Route path="/my-applications" component={MyApplications} />
                  <Route path="/public" component={PublicHome} />
                  <Route path="/admin" component={Admin} />
                  <Route path="/api-docs" component={ApiDocs} />
                  <Route path="/api-keys" component={ApiKeys} />
                  <Route path="/pdca" component={PDCACycles} />
                  <Route path="/transparency" component={PublicDashboard} />
                  <Route path="/scorecard/:systemId" component={ComplianceScorecard} />
                  <Route path="/knowledge-base" component={KnowledgeBase} />
                  <Route path="/enterprise-onboarding" component={EnterpriseOnboarding} />
                  <Route path="/pricing" component={Pricing} />
                  <Route path="/leaderboard" component={WatchdogLeaderboard} />
                  <Route path="/regulator" component={RegulatorDashboard} />
                  <Route path="/blog" component={Blog} />
                  <Route path="/recommendations" component={Recommendations} />
                  <Route path="/accreditation" component={Accreditation} />
                  <Route path="/soai-pdca" component={SOAIPDCAFramework} />
                  <Route path="/pdca-simulator" component={PDCASimulator} />
                  <Route path="/verify-certificate" component={CertificateVerification} />
                  <Route path="/enterprise" component={Enterprise} />
                  <Route path="/enterprise-dashboard" component={EnterpriseDashboard} />
                  <Route path="/compliance-monitoring" component={ComplianceMonitoring} />
                  <Route path="/bulk-import" component={BulkAISystemImport} />
                  {/* Legal Pages */}
                  <Route path="/membership-agreement" component={MembershipAgreement} />
                  <Route path="/legal/membership" component={MembershipAgreement} />
                  <Route path="/founding-council-agreement" component={FoundingCouncilAgreement} />
                  <Route path="/legal/founding-council" component={FoundingCouncilAgreement} />
                  <Route path="/licensing-agreement" component={LicensingAgreement} />
                  <Route path="/legal/licensing" component={LicensingAgreement} />
                  <Route path="/privacy-policy" component={PrivacyPolicy} />
                  <Route path="/privacy" component={PrivacyPolicy} />
                  <Route path="/legal/privacy" component={PrivacyPolicy} />
                  <Route path="/terms-of-service" component={TermsOfService} />
                  <Route path="/terms" component={TermsOfService} />
                  <Route path="/legal/terms" component={TermsOfService} />
                  <Route path="/disclaimers" component={Disclaimers} />
                  <Route path="/legal/disclaimers" component={Disclaimers} />
                  <Route path="/dpa" component={DataProcessingAgreement} />
                  <Route path="/data-processing-agreement" component={DataProcessingAgreement} />
                  <Route path="/legal/dpa" component={DataProcessingAgreement} />
                  <Route path="/cookies" component={CookiePolicy} />
                  <Route path="/cookie-policy" component={CookiePolicy} />
                  <Route path="/legal/cookies" component={CookiePolicy} />
                  <Route path="/sla" component={ServiceLevelAgreement} />
                  <Route path="/service-level-agreement" component={ServiceLevelAgreement} />
                  <Route path="/legal/sla" component={ServiceLevelAgreement} />
                  <Route path="/404" component={NotFound} />
                  {/* Final fallback route */}
                  <Route component={NotFound} />
                  </Switch>
                  </Suspense>
                </main>
                <Footer />
              </div>
              <Toaster
                position="top-right"
                toastOptions={{
                  style: {
                    background: 'hsl(var(--card))',
                    border: '1px solid hsl(var(--border))',
                    color: 'hsl(var(--foreground))',
                  },
                }}
              />
            </TooltipProvider>
          </AnalyticsProvider>
        </AuthProvider>
      </ThemeProvider>
    </ErrorBoundary>
  );
}

export default App;
