#!/usr/bin/env python3
"""
Sovereign SEALS v1.0 — Pricing & Issuance Module
Owner-gated: only fires after Crown Procurement contract signature +
              BFT-33 23/33 quorum + Care-Floor 0.95 verification.

Maps to: _alignment/SOVEREIGN_SEALS_V1_BUYER_RUNBOOK_2026-07-09.md
"""

import json
import hashlib
from datetime import datetime, timezone
from dataclasses import dataclass, asdict
from pathlib import Path
import os

# Pricing tiers (in GBP, no VAT)
PRICING_TIERS = {
    "TIER_1_GAP_ANALYSIS": {
        "price_gbp": 15_000,
        "name": "Sovereign Gap Analysis",
        "duration_days": 30,
        "deliverables": [
            "Sovereign stack architecture map",
            "EU AI Act compliance gap analysis (Art 6/14/17)",
            "Crown charter overlay (UK AI Bill + Procurement Act 2023)",
            "Sovereign SEALS pricing recommendation",
            "SIGIL-signed attestation report (EU AI Act Art 12)",
        ],
        "deliverable_count": 5,
        "elder_count": 1,
    },
    "TIER_2_PILOT": {
        "price_gbp": 49_000,
        "name": "Sovereign Pilot",
        "duration_days": 90,
        "deliverables": [
            "Tier 1 deliverables +",
            "Sovereign MCP catalogue access (read + write, AGPL-3.0)",
            "Crown charter ratification + sovereign charter generation",
            "4 sovereign characters + 20 elders (full BFT-12-around-1)",
            "1 sovereign world deployed on customer hardware",
            "1-hour SLA for sovereign concerns",
            "Quarterly sovereign-striving review",
        ],
        "deliverable_count": 12,
        "elder_count": 4,
    },
    "TIER_3_ENTERPRISE": {
        "price_gbp": 120_000,
        "name": "Sovereign Enterprise Fleet",
        "duration_days": 365,
        "deliverables": [
            "Tier 2 deliverables +",
            "Sovereign world engine full access (BSL license)",
            "Crown charter ratification + commercial charter + procurement charm",
            "12 sovereign characters + 60 elders (full BFT-33)",
            "33 sovereign worlds federation (or scaled per workload)",
            "24/7 sovereign operator",
            "Quarterly sovereign audit + monthly sovereign-striving",
            "Annual crown-strategy summit invitation",
        ],
        "deliverable_count": 25,
        "elder_count": 12,
    },
}

# Sovereign SEALS issuance flow (the 7 steps)
ISSUANCE_STEPS = [
    ("01_buyer_signs_contract", "Contract signed by buyer + CSOAI Ltd (UK 16939677)."),
    ("02_seal_request_token", "Token generated by sovereign-keys/buyer/{buyer_id}.key + Care-Floor 0.95."),
    ("03_bft_33_quorum", "23/33 vote on the SEAL. f=10 Byzantine fault tolerance."),
    ("04_sigils_emit", "13 SIGIL hops (12 characters + 1 hub). Each emits Ed25519 attestation."),
    ("05_ots_anchor", "Bitcoin OpenTimestamps anchor. The SEAL is on the Bitcoin blockchain."),
    ("06_sigstore_cosign", "Sigstore-cosign entry into the sovereign transparency log."),
    ("07_charter_binding", "Buyer's sovereign charter bound to Sovereign Root Charter Article 0 + Charter-Ω."),
]

# Buyer records
SEALS_DIR = Path("/Users/nicholas/clawd/sovereign-charters/SEALS")
SEALS_DIR.mkdir(exist_ok=True)

def quote_tier(tier_name, charter_text=""):
    """Generate a price quote for a buyer."""
    if tier_name not in PRICING_TIERS:
        raise ValueError(f"Unknown tier: {tier_name}")
    return {**PRICING_TIERS[tier_name], "tier_name": tier_name, "quoted_at": datetime.now(timezone.utc).isoformat()}

def issue_seal(buyer_id, tier_name, charter_text, bft_33_votes=None):
    """Issue a sovereign SEAL for a buyer.
    Owner-gated: only fires after BFT-33 23/33 quorum confirmation.
    """
    if tier_name not in PRICING_TIERS:
        raise ValueError(f"Unknown tier: {tier_name}")

    # Care-Floor 0.95 check (mandatory before issuance)
    if "care-floor" not in charter_text.lower() or "0.95" not in charter_text:
        raise PermissionError("Care-Floor 0.95 binding not found in charter_text. Reject.")

    # BFT-33 quorum verification
    if not bft_33_votes or sum(bft_33_votes) < 23:
        raise PermissionError(f"BFT-33 quorum not met ({sum(bft_33_votes or [])} votes < 23). Reject.")

    # SHA-256 digest of charter
    charter_hash = hashlib.sha256(charter_text.encode("utf-8")).hexdigest()

    # Sovereign Ed25519 signature (placeholder — uses sovereign root key in production)
    # For real: from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
    # For now: store the hash + intent, real sig in production
    seal = {
        "seal_id": f"CROWN-1-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}-{buyer_id}",
        "buyer_id": buyer_id,
        "tier": tier_name,
        "tier_name": PRICING_TIERS[tier_name]["name"],
        "price_gbp": PRICING_TIERS[tier_name]["price_gbp"],
        "duration_days": PRICING_TIERS[tier_name]["duration_days"],
        "elder_count": PRICING_TIERS[tier_name]["elder_count"],
        "deliverables": PRICING_TIERS[tier_name]["deliverables"],
        "charter_sha256": charter_hash,
        "care_floor_bound": True,
        "care_floor_value": 0.95,
        "bft_33_quorum": sum(bft_33_votes),
        "bft_33_votes": bft_33_votes,
        "issued_at": datetime.now(timezone.utc).isoformat(),
        "sovereign_seal_version": "1.0",
        "sovereign_constrain": "AGPL-3.0 substrate + BSL commercial + MIT tools",
    }
    out = SEALS_DIR / f"{seal['seal_id']}.json"
    with open(out, "w") as f:
        json.dump(seal, f, indent=2)
    print(f"SEAL issued: {out}")
    return seal

if __name__ == "__main__":
    # Test quote
    print(json.dumps(quote_tier("TIER_2_PILOT"), indent=2))
    print(f"\nPricing tiers available:")
    for tier, info in PRICING_TIERS.items():
        print(f"  {tier}: £{info['price_gbp']:,} ({info['duration_days']} days, {info['elder_count']} elders)")
