/**
 * attest-verify — external Ed25519 card verifier (Cloudflare Worker).
 *
 * Re-homes the estate's verifier off the billing-blocked Vercel endpoint onto
 * a free Cloudflare Worker. Verifies the Ed25519-SIGNED measurement cards
 * (from sovos-city chain.py / card_issuer) WITHOUT any secret — the whole point
 * of asymmetric signatures.
 *
 * A third party can POST any card and get an honest {valid, signer,
 * content_id_matches} without trusting us. This is what makes the signed-card
 * issuance leg verifiable externally — the thing all four attestation markets
 * sell.
 *
 * Verification model (must match chain.py exactly):
 *   body_recomputed  = canonical(JSON stringify with sorted keys, no spaces)
 *   content_id       = sha256(body_with_prev_epoch)
 *   valid            = Ed25519(pubkey).verify(signature, content_id)
 *
 * Endpoints:
 *   GET  /            -> service info
 *   POST /verify      -> body = card JSON { body, signature, pubkey, content_id }
 *   GET  /pubkey      -> the estate public key (kid: ed25519:...)
 */
// CF Workers expose WebCrypto (crypto.subtle) — Ed25519 + SHA-256 are native.
// No node:crypto (unavailable in Workers). Verification needs no secret.

async function canonicalStringify(obj) {
  // deterministic: sorted keys, no spaces, same as Python json.dumps(sort_keys,
  // separators=(",",":"), ensure_ascii=False) for the boolean/null/string/number
  // shapes that appear in cards.
  if (Array.isArray(obj)) {
    const parts = [];
    for (const v of obj) parts.push(await canonicalStringify(v));
    return "[" + parts.join(",") + "]";
  }
  if (obj && typeof obj === "object") {
    const keys = Object.keys(obj).sort();
    const parts = [];
    for (const k of keys) {
      const v = obj[k];
      if (v === undefined) continue;
      const ks = JSON.stringify(k);
      const vs = await canonicalStringify(v);
      parts.push(ks + ":" + vs);
    }
    return "{" + parts.join(",") + "}";
  }
  return JSON.stringify(obj);
}

async function sha256Hex(str) {
  const buf = new TextEncoder().encode(str);
  const digest = await crypto.subtle.digest("SHA-256", buf);
  return Array.from(new Uint8Array(digest)).map((b) => b.toString(16).padStart(2, "0")).join("");
}

async function verifyEd25519(pubkeyHex, sigHex, msgStr) {
  try {
    const keyBytes = new Uint8Array(
      pubkeyHex.match(/[0-9a-fA-F]{2}/g).map((b) => parseInt(b, 16))
    );
    const sigBytes = new Uint8Array(
      sigHex.match(/[0-9a-fA-F]{2}/g).map((b) => parseInt(b, 16))
    );
    const key = await crypto.subtle.importKey(
      "raw", keyBytes, { name: "Ed25519" }, false, ["verify"]
    );
    const ok = await crypto.subtle.verify(
      "Ed25519", key, sigBytes, new TextEncoder().encode(msgStr)
    );
    return ok;
  } catch (e) {
    return false;
  }
}

// The COMMITTED did:web identity document (./.well-known/did.json in this repo).
// Served verbatim so did:web:csoai.org resolves at csoai.org/.well-known/did.json
// even while the Pages custom-domain attach is pending (token lacks Zone DNS Edit).
// If did.json changes, regenerate via make_did.py on the production keystone,
// commit, and redeploy this worker — never edit this constant by hand.
const DID_JSON = {"@context":["https://www.w3.org/ns/did/v1","https://w3id.org/security/suites/jws-2020/v1","https://w3id.org/security/suites/ed25519-2020/v1"],"id":"did:web:csoai.org","verificationMethod":[{"id":"did:web:csoai.org#keys-1","type":"JsonWebKey2020","controller":"did:web:csoai.org","publicKeyJwk":{"kty":"OKP","crv":"Ed25519","x":"9LQnjdwhbC8GCyc6_P2e8AhWOZNzsjsJd5T-cvs2w0I","kid":"csoai-city-ed25519-1","use":"sig"}},{"id":"did:web:csoai.org#keys-2","type":"Ed25519VerificationKey2020","controller":"did:web:csoai.org","publicKeyMultibase":"z6MkvvUrSjViFsHuL4gL1rpAE8NLEnNg7sWWjoUWaX289zqF"}],"assertionMethod":["did:web:csoai.org#keys-1","did:web:csoai.org#keys-2"],"authentication":["did:web:csoai.org#keys-1"],"service":[{"id":"did:web:csoai.org#verifier","type":"AttestationVerifier","serviceEndpoint":"https://csoai.org/verify"}],"_note":"CSOAI signing identity. Ed25519 today (ML-DSA-65 is roadmap, not present). Generated by make_did.py from the signing keystone — regenerate on the production keystone so the published key equals the one that signs. C2PA-trust-list / CA recognition is a separate owner-gated step, not claimed here."};

function jsonResponse(obj, status = 200) {
  return new Response(JSON.stringify(obj, null, 2), {
    status,
    headers: {
      "Content-Type": "application/json",
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type",
    },
  });
}

export default {
  async fetch(request) {
    const url = new URL(request.url);

    if (request.method === "OPTIONS") {
      return jsonResponse({ ok: true });
    }

    // GET / -> service info
    if (request.method === "GET" && (url.pathname === "/" || url.pathname === "/health")) {
      return jsonResponse({
        service: "csoai-attest-verify",
        version: "1.0.0",
        scheme: "Ed25519 (FIPS-compatible asymmetric)",
        note: "external verification without secret — same model as chain.py",
      });
    }

    // GET /.well-known/did.json -> the committed did:web identity document
    if (request.method === "GET" && url.pathname === "/.well-known/did.json") {
      return new Response(JSON.stringify(DID_JSON, null, 2), {
        status: 200,
        headers: {
          "Content-Type": "application/did+ld+json",
          "Access-Control-Allow-Origin": "*",
          "Cache-Control": "public, max-age=300",
        },
      });
    }

    // POST /verify
    if (request.method === "POST" && url.pathname === "/verify") {
      let card;
      try {
        card = await request.json();
      } catch (e) {
        return jsonResponse({ valid: false, error: "invalid JSON body" }, 400);
      }
      if (!card || typeof card !== "object") {
        return jsonResponse({ valid: false, error: "card must be an object" }, 400);
      }

      const body = card.body;
      const signature = card.signature;
      const pubkey = card.pubkey || card.signer;   // card_issuer stores pubkey as `signer`
      const claimedContentId = card.content_id;

      if (!body || !signature || !pubkey) {
        return jsonResponse({
          valid: false,
          error: "card missing body/signature/pubkey",
          hint: "sanitised: only fully-formed Ed25519 cards verify",
        }, 400);
      }

      try {
        // 1. recompute canonical body -> content_id (match chain.py)
        const canon = await canonicalStringify(body);
        const recomputed = await sha256Hex(canon);

        // 2. verify the signature over the RECOMPUTED content id (not the claimed one)
        const sigOk = await verifyEd25519(pubkey, signature, recomputed);

        // 3. also confirm the claimed content_id matches (defence against a
        //    replayed card asserting a stale id)
        const cidMatch = recomputed === String(claimedContentId);

        return jsonResponse({
          valid: cidMatch && sigOk,
          signer: "ed25519:" + String(pubkey).slice(0, 16),
          content_id: recomputed,
          content_id_matches: cidMatch,
          signature_valid: sigOk,
          note: cidMatch && sigOk ? "card verified: measurement record intact" :
                "card FAILED verification: content or signature does not match",
        });
      } catch (e) {
        return jsonResponse({ valid: false, error: "verification error: " + e.message }, 500);
      }
    }

    return jsonResponse({ valid: false, error: "not found" }, 404);
  },
};
