#!/bin/bash
# BATCH DATA-BINDING PATCHER
# Adds the "World's Data" data-binding section to all industry charters
# that don't already have it.

set -e

CHARTER_DIR="/Users/nicholas/clawd/sovereign-charters"

# The text to insert
DATA_BINDING='
## DATA BINDING — THE WORLD'\''S DATA (49GB SOVEREIGN MOAT)

This charter inherits the L0 Sovereign Root binding to the sovereign data moat: **49GB total** (25GB organic + 9GB extracted 17 Jun + 15GB partner data), **198 live data sources** across 8 categories, **30+ live feeds** (UK Companies House, Land Registry, NVD, MITRE ATLAS, Reuters AI, etc.), **4,721 files** SHA-256 hashed with OTS Bitcoin proof, and **532K synthetic records** generated by synthetic-data-factory.

**The 8 data categories**:
1. **Government** (12 sources) — UK Companies House, Land Registry, OS Open Names, DVSA MOT, HSE RIDDOR, EA Flood, Met Office, EU AI Office, US OSTP, etc.
2. **Standards** (8) — ISO, IEEE, NIST, BSI, IETF, W3C, ETSI, NCSC
3. **Industry** (45) — Companies House PSC, Land Registry price-paid, trade data
4. **Vulnerability** (6) — NVD CVE, GitHub Advisory, OSV, MITRE ATLAS, OWASP, Exploit-DB
5. **Academic** (18) — arXiv, PubMed, PsyArXiv, SocArXiv, Cochrane, Campbell, FAccT, NeurIPS, ICML
6. **News** (27) — Reuters, FT, BBC, MIT Tech Review, Wired, The Verge, TechCrunch, The Register
7. **Court** (5) — CourtListener, BAILII, EUR-Lex, ICO, BfDI
8. **Vendor** (35) — OpenAI, Anthropic, DeepMind, Mistral, Meta AI, Google, Microsoft, Cohere, AI21

**Data Sovereignty Guarantees**: All data UK-resident. No cross-border transfer without Charter Article 0 binding. GDPR-compliant (data subject rights, DSAR support, right to erasure). Open data only. OTS-anchored. Synthetic augmentation (532K records). Every charter inherits this binding.

**The 30 Universal Compliance Frameworks** (cross-walked at L0): EU AI Act (Art 5, 10, 50, Annex III) · GDPR (Art 5-21) · ISO/IEC 42001:2023 · ISO/IEC 27001:2022 · ISO/IEC 23894:2023 · NIST AI RMF 1.0 · NIST CSF 2.0 · SOC 2 Type II · HIPAA · DORA (EU 2022/2554) · CSRD/ESRS · UK AI Regulation · UK DPA 2018 · Colorado AI Act · California CPPA AI · NIST SP 800-53 Rev 5 · NIST SP 800-171 Rev 3 · FedRAMP · PCI DSS v4.0 · CMMC 2.0 · MITRE ATLAS · OWASP Top 10 for LLMs · IEEE 7000-2021 · ISO/IEC 38507:2022 · BSI PAS 1880:2020 · Singapore AI Verify · Canada AIDA · UNESCO AI Ethics · OECD AI Principles · G7 Hiroshima AI Process.
'

PATCHED=0
SKIPPED=0
ERRORS=0

# Process all 35 industry charters
for f in $CHARTER_DIR/[0-9][0-9]-*-charter.md; do
    # Skip if already has DATA BINDING section
    if grep -q "DATA BINDING" "$f" 2>/dev/null; then
        echo "  SKIP (already has DATA BINDING): $f"
        SKIPPED=$((SKIPPED+1))
        continue
    fi

    # Find the first "## ARTICLE" heading to insert before it
    ANCHOR=$(grep -n "^## ARTICLE" "$f" | head -1 | cut -d: -f1)

    if [ -z "$ANCHOR" ]; then
        # No ARTICLE heading — append to end
        printf "\n%s" "$DATA_BINDING" >> "$f"
        echo "  APPEND (no ARTICLE anchor): $f"
    else
        # Insert before the ARTICLE heading using head + tail
        head -n $((ANCHOR - 1)) "$f" > /tmp/charter.tmp
        printf "%s\n" "$DATA_BINDING" >> /tmp/charter.tmp
        tail -n +$ANCHOR "$f" >> /tmp/charter.tmp
        mv /tmp/charter.tmp "$f"
        echo "  PATCHED (before line $ANCHOR): $f"
    fi

    PATCHED=$((PATCHED+1))
done

echo ""
echo "============================================"
echo "  PATCHED: $PATCHED"
echo "  SKIPPED: $SKIPPED"
echo "  ERRORS:  $ERRORS"
echo "============================================"