#!/bin/bash
# daily-metrics.sh — CSOAI daily sales/revenue snapshot
# Phase 533 stub · Author: Hermes subagent · 2026-07-08
#
# What it does (manual run today; cron wiring staged for Nick):
#   1. Counts signup entries (line count of /tmp/signups.jsonl on Vercel — proxied via local mirror, or API hit count)
#   2. Counts MRC/active customers (Stripe placeholder — not yet live)
#   3. Computes total signups today, week, all-time
#   4. Appends to MRR_TRACKER.md (append-only ledger)
#   5. Sleeps + repeats (loop disabled in stub — runs once when invoked)
#   6. Output is a 5-line markdown table
#
# EAT 2026-07-02 compliance: NO Stripe API calls, NO webhook calls, NO deploys.
# This is a STUB — the data sources are placeholders. Nick wires real ones once Stripe flips (Gate A).

set -euo pipefail

# ---- CONFIG (staged for owner-gated wiring) ---------------------------------
EXEC_DIR="/Users/nicholas/clawd/csoai-launch-pack/EXEC"
TRACKER="$EXEC_DIR/MRR_TRACKER.md"
SIGNUPS_LOCAL="/tmp/csoai-signups.mirror.jsonl"     # local mirror placeholder
STRIPE_KEY="${STRIPE_SECRET_KEY:-unset}"            # unset until Gate A flips
SIGNUP_API="https://csoai-static-deploy2.vercel.app/api/signup"  # live count proxy

# ---- DATE UTILS --------------------------------------------------------------
TODAY="$(date -u +%Y-%m-%d)"
WEEK_AGO="$(date -u -v-7d +%Y-%m-%d 2>/dev/null || date -u --date='7 days ago' +%Y-%m-%d)"
TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# ---- DATA GATHERING ---------------------------------------------------------

# Signups: try local mirror first; fall back to API hit count; fall back to 0
if [ -f "$SIGNUPS_LOCAL" ]; then
    TOTAL_SIGNUPS=$(wc -l < "$SIGNUPS_LOCAL" | tr -d ' ')
    WEEK_SIGNUPS=$(awk -v cutoff="$WEEK_AGO" -v today="$TODAY" '
        $0 ~ today {c++}
        END {print c+0}
    ' "$SIGNUPS_LOCAL")
    TODAY_SIGNUPS=$(awk -v today="$TODAY" 'BEGIN{c=0} $0 ~ today {c++} END{print c}' "$SIGNUPS_LOCAL")
else
    # Try API — Vercel /api/signup may not exist; if 404, treat as 0
    API_STATUS=$(curl -s -o /dev/null -w '%{http_code}' "$SIGNUP_API" 2>/dev/null || echo "000")
    if [ "$API_STATUS" = "200" ]; then
        BODY=$(curl -sS "$SIGNUP_API" 2>/dev/null || echo '{"count":0,"week":0,"today":0}')
        TOTAL_SIGNUPS=$(echo "$BODY" | grep -oE '"count":[0-9]+' | head -1 | grep -oE '[0-9]+' || echo 0)
        WEEK_SIGNUPS=$(echo "$BODY" | grep -oE '"week":[0-9]+' | head -1 | grep -oE '[0-9]+' || echo 0)
        TODAY_SIGNUPS=$(echo "$BODY" | grep -oE '"today":[0-9]+' | head -1 | grep -oE '[0-9]+' || echo 0)
    else
        # Honest placeholder: no live data source available
        TOTAL_SIGNUPS="0 (placeholder — /tmp/csoai-signups.mirror.jsonl not yet piped from Vercel /api/signup; API returned HTTP $API_STATUS)"
        WEEK_SIGNUPS="0 (placeholder)"
        TODAY_SIGNUPS="0 (placeholder)"
    fi
fi

# MRC / customers: Stripe not yet live — honest placeholder
if [ "$STRIPE_KEY" = "unset" ] || [ -z "$STRIPE_KEY" ]; then
    MRC="£0 (placeholder — Stripe not yet wired; Gate A flip in EXEC_DASHBOARD unblocks this)"
    ACTIVE_CUSTOMERS="0 (placeholder — depends on Gate A Stripe flip)"
else
    # Live code path (commented until Gate A flips):
    # ACTIVE_CUSTOMERS=$(curl -sS -u "$STRIPE_KEY:" "https://api.stripe.com/v1/subscriptions?status=active&limit=100" \
    #                     | grep -oE '"id":"sub_[^"]+"' | wc -l | tr -d ' ')
    # MRC=$(curl -sS -u "$STRIPE_KEY:" "https://api.stripe.com/v1/subscriptions?status=active&limit=100" \
    #       | python3 -c 'import json,sys; d=json.load(sys.stdin); m=sum(i["items"]["data"][0]["price"]["unit_amount"] for i in d["data"] if i["items"]["data"]); print(f"£{m/100:,.0f}")')
    MRC="£0 (Stripe live, code path commented above)"
    ACTIVE_CUSTOMERS="0 (Stripe live, code path commented above)"
fi

# ---- 5-LINE TABLE -----------------------------------------------------------
TABLE=$(cat <<EOF
| Date (UTC) | Today | Week (${WEEK_AGO}→${TODAY}) | All-time | MRR | Active customers |
|---|---|---|---|---|---|
| ${TODAY} | ${TODAY_SIGNUPS} | ${WEEK_SIGNUPS} | ${TOTAL_SIGNUPS} | ${MRC} | ${ACTIVE_CUSTOMERS} |
EOF
)

# ---- WRITE / APPEND ---------------------------------------------------------
mkdir -p "$EXEC_DIR"

if [ ! -f "$TRACKER" ]; then
    printf "# CSOAI MRR Tracker (append-only ledger)\n\n" > "$TRACKER"
    printf "_Generated by daily-metrics.sh stub · Phase 533 · 2026-07-08 · EAT 2026-07-02 stage-only_\n\n" >> "$TRACKER"
    printf "Each row = one daily snapshot. Source: %s / Stripe placeholder.\n\n" "$SIGNUPS_LOCAL" >> "$TRACKER"
fi

printf "## %s snapshot — %s\n\n" "$TODAY" "$TS" >> "$TRACKER"
printf '```\n%s\n```\n\n' "$TABLE" >> "$TRACKER"

# ---- STDOUT (for cron email / terminal) -------------------------------------
echo "$TABLE"
echo
echo "[stub] appended to $TRACKER"
echo "[stub] next: wire Stripe key (Gate A flip in EXEC_DASHBOARD) to unblock MRC + active-customer columns"

# ---- LOOP (disabled in stub) -----------------------------------------------
# Per task spec: "Sleeps + repeats (set up as a manual run, not actually scheduled)"
# The stub runs ONCE and exits. To enable periodic execution, wrap the body in:
#
#   while true; do
#     ...body above...
#     sleep 86400   # 24h
#   done
#
# and install via launchd (LaunchAgent plist in ~/Library/LaunchAgents/).
# NOT scheduled today per EAT directive.
exit 0
