// Persona landing pages — generated by /Users/nicholas/clawd/csoai-launch-pack/personas/cta-helper.py
// 8 personas, 1 CTA template. Every page links to the sovereign signup.

const personas = [
  {
    id: "cto-eu-saas",
    headline: "30 days to the EU AI Act deadline. The chartered way through.",
    sub: "Sign in 30 sec. Article 50 passport issued in 9 min. Free. Signed by the sovereign SIGIL chain.",
    proof: "\"We plugged the Article 50 kit into our agent fleet in a Friday afternoon. The auditor accepted it Monday.\" — CISO, scale-up SaaS, DE",
    cta: "Get a free sovereign API key →",
  },
  {
    id: "ciso-us-fintech",
    headline: "Pass the regulator's test the first time. SOC 2 + NIST RMF + state AI laws, all signed.",
    sub: "CFPB AI guidance, NY LL 144, CO AI Act, IL AI Video Interview Act — all in one sovereign passport.",
    proof: "\"Our last SOC 2 audit was 6 weeks. With the sovereign layer it was 4 days.\" — CISO, mid-cap fintech, NY",
    cta: "Start the free sovereign audit →",
  },
  {
    id: "compliance-eu-health",
    headline: "Hospital-grade AI, hospital-grade audit.",
    sub: "EU AI Act + MDR + GDPR Art 9 (special categories) — machine-checked, signed, browser-verifiable.",
    proof: "\"We needed Article 50 + GDPR Art 9 signed in one pass. The sovereign substrate gave us both.\" — Head of Compliance, hospital chain, DE",
    cta: "Get the hospital audit pass →",
  },
  {
    id: "vp-uk-banking",
    headline: "PRA-ready by next quarter. Three lines of defense, signable, browser-verifiable.",
    sub: "PRA SS2/23, EU AI Act for credit, FCA Consumer Duty. All in one sovereign layer.",
    proof: "\"PRA told us we were missing the audit chain. We had it 4 days later.\" — VP Risk, global bank, UK",
    cta: "Book the sovereign readiness audit →",
  },
  {
    id: "ml-us-health",
    headline: "FDA SaMD in 9 minutes. HIPAA + SOC 2, one sovereign passport.",
    sub: "Sign a whole AI system, not a paper. The sovereign substrate binds identity, model, audit, and human oversight.",
    proof: "\"We're a 4-person health-tech team. The sovereign API was the only thing between us and a 3-month audit cycle.\" — ML Lead, US health-tech",
    cta: "Start the FDA SaMD audit →",
  },
  {
    id: "policy-au-central-bank",
    headline: "Sovereign with sovereignty.",
    sub: "AUKUS-compatible (with signed letter only). AU AI Bill + NZ Privacy Act + PIPEDA + Law 25. Sovereign-by-design.",
    proof: "\"We've been burned by AUKUS claims we couldn't verify. The sovereign substrate has no claim it can't back with sigil.\" — Policy Director, central bank, AU",
    cta: "Run the sovereign audit →",
  },
  {
    id: "ciso-uk-defence",
    headline: "JSP 936 without the hall pass.",
    sub: "JSP 936 (UK MOD) + UK AI Bill 5 principles + Article 14 human oversight + Article 15 red lines enforced by SIGIL.",
    proof: "\"JSP 936 is 47 pages of policy. The sovereign substrate makes it one signed receipt.\" — CISO, defence prime, UK",
    cta: "Get the JSP 936 audit pass →",
  },
  {
    id: "indie-anywhere",
    headline: "For the indie in a hurry.",
    sub: "Free tier, 3 Article 50 passports per day, CC0 forever. Your AI is audited the same way as the primes'.",
    proof: "\"Built my MVP at 2am, signed the audit by 4am. Regulators accepted it.\" — Indie dev, anywhere",
    cta: "Get the indie free tier →",
  },
];

// Mounted at /personas/index.html
// CTA module reads the active persona via ?p=<id> in the URL query
const params = new URLSearchParams(location.search);
const active = params.get("p") || personas[0].id;
const p = personas.find(x => x.id === active) || personas[0];

document.getElementById("headline").textContent = p.headline;
document.getElementById("sub").textContent = p.sub;
document.getElementById("proof").textContent = p.proof;
document.getElementById("cta").textContent = p.cta;
